### PR TITLE
fix(rslint_lexer): Upgrade to the latest unicode table

### PR DESCRIPTION
**Pull request by Boshen**
## Summary

This table is automatically generated by running `rslint_lexer/scripts/gen.py`

## Test Plan
A couple of fixes on Unicode 14 within test262.

### CODE REVIEW

**Comment by Boshen** [comment]
Both bot comment failed, here is the output: 

  | Test result | `main` count | This PR count | Difference |
  | :---------: | :----------: | :-----------: | :--------: |
  | Total | 44951 | 44951 | 0 |
  | Passed | 42866 | 42870 | ✅ ⏫ **+4** |
  | Failed | 2084 | 2080 | ✅ ⏬ **-4** |
  | Panics | 1 | 1 | 0 |
  | Coverage | 95.36% | 95.37% | **+0.01%** |
  
  <details><summary><b>:tada: Fixed (4):</b></summary>
  
  ```
  xtask/src/coverage/test262/test\language\identifiers\part-unicode-14.0.0-escaped.js
  xtask/src/coverage/test262/test\language\identifiers\part-unicode-14.0.0.js
  xtask/src/coverage/test262/test\language\identifiers\start-unicode-14.0.0-escaped.js
  xtask/src/coverage/test262/test\language\identifiers\start-unicode-14.0.0.js
  ```
  </details>

**Comment by MichaReiser** [comment]
Nice! I didn't know we have a command to update the unicode table. Would you mind adding a comment to the `Contributing.md` or maybe, even better, add a comment with the name of the command at the top of the `crates/rslint_lexer/src/tables.rs`?

**Comment by Boshen** [comment]
Rebased on https://github.com/rome/tools/pull/1911 to test CI changes

**Review by MichaReiser — APPROVED** [review]

**Comment by ematipico** [comment]
It seems that running this script requires having python installed to the contributor's machine. We should update the internal documentation. 

Although, I wonder if it's worth moving the script to Rust at this point?

**Pull request merged**
