### PR TITLE
feat: add (and enable) --changed support to the ci CLI command

### LINKED ISSUE #978: 📎 Enable `--changed` for `check` by default in `rome ci`
Would lead to a small performance increase for `rome ci` and should be relatively safe. (`rome test` takes up a **significant** portion of a `rome ci` run)

### LINKED ISSUE #1087: 📎 Gracefully handle failing VSC getUncommittedFiles and getModifiedFiles
See #1073 for relevant discussion.

We could do one of three things:

1. What we do now: throw a hard error. But make it more descriptive. We don't even include the method name right now.
2. Log an error, and return an empty array.
3. Log an error, and return something else besides an array when we aren't sure or fail.

### PR DESCRIPTION
**Pull request by bitpshr**
## Summary

This pull request updates the `rome ci` command to accept a `--changed` flag that's in turn passed through to the underlying `rome check` command. This approach should safely allow unnecessary file checks to be avoided, leading to a reduced `rome ci` execution time.

This flag has been enabled for Rome's internal GitHub action.

Resolves #978
Resolves #1087

## Test Plan

```sh
>   ./rome test
```

### CODE REVIEW

**Comment by sebmck** [comment]
Nice! Looks like it's failing though. I wonder if it's because GitHub Actions only does a shallow clone and might not have the necessary information to make the comparison.

**Comment by sebmck** [comment]
Ah yeah, that's probably it. It uses `depth=1` by default. Looks like it can be configured with `fetch-depth: 0` though to fetch the entire history, not sure how much time that would add to the checkout. https://github.com/actions/checkout

**Comment by sebmck** [comment]
Opened #1087 to track making the git failure more actionable/descriptive.

**Comment by bitpshr** [comment]
Thanks for the review @sebmck. I updated the fetch depth and attempted to smooth out VSC error handling for `GitVCSClient#getMainBranch`, `GitVCSClient#getUncommittedFiles`, and `GitVCSClient#getModifiedFiles` per #1087. For some reason all VCS commands are still failing. I'll dig more.

**Comment by ematipico** [comment]
@jamiebuilds that's the one. It seems the CI was failing and it needed more work, that's why it wasn't merged.

**Comment by jamiebuilds** [comment]
Hi! Thank you so much for your contribution!

We recently made the decision to [migrate the Rome codebase to Rust](https://rome.tools/blog/2021/09/21/rome-will-be-rewritten-in-rust) and making some significant changes to its architecture.

We're going through and closing pull requests and issues that were specific to the TypeScript codebase, including this one. But while we're closing this, we'd love to have your involvement in the future.

Thanks again!

**Pull request closed without merging**
