### PR TITLE
doc(website): Run `cargo lintdoc`

### PR DESCRIPTION
**Pull request by 95th**
## Summary

`cargo lintdoc` output is dirty.

Resolves:
* https://github.com/rome/tools/issues/3566 

## Test Plan

None

### CODE REVIEW

**Comment by ematipico** [comment]
Also this file needs to be updated https://github.com/rome/tools/blob/main/crates/rome_diagnostics_categories/src/categories.rs

**Comment by 95th** [comment]
@ematipico Do you mean the category keys? the links seem to be already pointing to `https://rome.tools/docs/..`

**Comment by MichaReiser** [comment]
@sebmck can you have a look at this PR please.

**Comment by ematipico** [comment]
> @ematipico Do you mean the category keys? the links seem to be already pointing to `https://rome.tools/docs/..`

The URL of the rules have changed since we changed the website, and this is something we missed. (this is on us) This is the new URL of the rules: https://docs.rome.tools/lint/rules/usealttext/

If you go to the page, check one of the diagnostics and click the link rendered (the name of the rule), it points to an URL that returns 404.

**Comment by ematipico** [comment]
Here's the error returned by Netlify: 


```block
2:00:53 PM: > build:styles
2:00:53 PM: > sass --style=compressed src/styles:src/_includes/styles
2:00:54 PM: [11ty] Problem writing Eleventy templates: (more in DEBUG output)
2:00:54 PM: [11ty] You’re trying to use a layout that does not exist: layouts/docs.liquid (undefined) (via Error)
2:00:54 PM: [11ty]
2:00:54 PM: [11ty] Original error stack trace: Error: You’re trying to use a layout that does not exist: layouts/docs.liquid 
```

**Comment by 95th** [comment]
> docs.liquid

How do I fix this error?

**Comment by 95th** [comment]
@ematipico Updated. please take a look

**Review by MichaReiser — APPROVED** [review]
Awesome, thank you

**Pull request merged**
