### PR TITLE
refactor(rome_js_analyze): enable the recommended nursery rules on unstable builds

### PR DESCRIPTION
**Pull request by leops**
## Summary

This PR refactors the `rome_flags` crate to replace the previous dynamic approach to feature flags (that was unused as it was hard to test correctly) with a static approach where the value of flags like `is_unstable` is determined at compilation time.

This unstable flag is now used in `rome_service` to enabled recommended rules from the nursery group by default on unstable builds. In order to test this change I've marked all the existing nursery rules as recommended, but that may not be appropriate for all rules so we could decide to downgrade some of them before they get stabilized.

Additionally I've also adjusted the logic used to determine which rules should be enabled to allow users to enable the recommended rules from a group without enabling all the recommended rules (eg. `{ "rules": { "recommended": false, "correctness": { "recommended": true } } }`

## Test Plan

I've added two new test to check that nursery rules are enabled in unstable builds (cargo tests should always be built as unstable), and that nesting the `recommended` setting works correctly

### CODE REVIEW

**Review by ematipico — CHANGES_REQUESTED** [review]
We would need to update the [contribution guidelines](https://github.com/rome/tools/blob/main/crates/rome_analyze/CONTRIBUTING.md#lint-rules) and explain why a nursery rule should be marked as `recommended` and why it's safe to do so.

**Review by MichaReiser — APPROVED** [review]
Does the lint rule dropdown on the playground become obsolete because of this change? If so, can you remove it?

**Comment by leops** [comment]
> Does the lint rule dropdown on the playground become obsolete because of this change? If so, can you remove it?

I didn't necessarily intend to include the playground in this change, but it makes sense that it ended up being included anyway as the playground is always using the latest main so it's technically an unstable build. Ideally I think we should retain the existing behavior for the playground though, where only stable rules are enabled by default but the user can opt-in to enable everything.

**Review by ematipico — APPROVED** [review]
In particular, we should update this line https://github.com/rome/tools/blob/main/crates/rome_analyze/CONTRIBUTING.md#L55 and explain why it's safe for a contributor to make a nursery rule recommended, e.g. mention that lint rules become un-recommended via feature flags in production.

**Review by ematipico — DISMISSED** [review]
Sorry, I just noticed that the documentation emitted is wrong, now all the rules, nursery too, are showed as recommended on the website

**Comment by Conaclos** [comment]
`noConstEnum` should probably be marked as recommended. The merge was done just after this PR was opened.

**Review by ematipico — COMMENTED** [review]
I don't want to block the PR, but there's still something that doesn't feel right. 

The updated contribution guidelines now say - rightfully - that rules that are meant to catch errors, should be recommended, and that **`nursery`** rules should be recommended without issue because they are un-recommended.

Although we are enabling ALL rules, which goes against what we said before. I think I am missing something... When do we deem a rule to be recommended? When do we decide if a rule catches bugs? 

Isn't it more natural to have `nursery` have rules `recommended: false` and then make them recommended only in debug builds? I fear that how things are worded and how's the code, could confuse people (I am confused).

For example now all the diagnostic of nursery rules show **errors**, which is wrong. They should show warnings unless told otherwise (change the severity via config).

**Comment by leops** [comment]
> Although we are enabling ALL rules, which goes against what we said before. I think I am missing something... When do we deem a rule to be recommended? When do we decide if a rule catches bugs?

We're not enabling all rules, only those that are recommended, so I specifically left out mentioning "when" determining whether a rule is recommended should be done from the documentation precisely because it should be done from the start when the rule is initially created. What this new approach does is bring us more usage information from the unstable builds, so we could decide to remove a rule from the recommended set before stabilizing it, if it turns out that it gets in the way of writing code more than help in catching actual errors.

> Isn't it more natural to have `nursery` have rules `recommended: false` and then make them recommended only in debug builds? I fear that how things are worded and how's the code, could confuse people (I am confused).

We can't really have the nursery rules marked as `recommended: false`, since we wouldn't know which rules should be enabled on unstable builds. We'd have to maintain a separate list of recommended nursery rules, and remove entries from that list and mark the rule as actually recommended when it gets stabilized which seemed unnecessarily complex when we could have marked the rule as recommended from the start.

> For example now all the diagnostic of nursery rules **in the website** show **errors**, _which feels wrong_. They should show warnings unless told otherwise (change the severity via config).

I'm not really sure why it would feel wrong in general, if a rule is recommended according to the documentation that means it's supposed to catch actual programming error, so `Error` is the correct severity for those. Now if emitting error diagnostics feels wrong for a specific rule, that's an important feedback, it means the rule probably shouldn't be recommended as it's not actually catching an error.

**Comment by ematipico** [comment]
@leops I read your reply, and it's now clear what's missing, from my prospective, with this PR. Bear with me while I explain what's going on, I try to make this clear: 

1. The PR is meant to change how `nursery` rules are enabled for **nightly builds**; that's what the title says. Nightly builds don't reflect production builds.
2. The description of the PR highlights the technical details to reach that.
3. Although, it seems that there are also changes to the contribution guidelines **and the website, which is the _mirror of our production releases_**, not nightly builds.

From our *unwritten* practices, we agreed that:

5. Recommended rules should emit errors
6. Rules that are not recommended, should emit warnings

From our documentation on the website, we state that `nursery` rules are unstable, hence they should be recommended. 

___

Now, from our discussion **and** the changes of the PR, it seems we are changing things in production too, we are actually changing things on the website. Although, these changes **aren't actually reflected anywhere on our website**. Here's what: 
- we don't explain why **some** `nursery` rules show `Error` instead of a warning, while we explained them [otherwise](https://docs.rome.tools/lint/rules/#nursery) 
> New rules that are still under development.

- now some `nursery` rules are shown as not recommended but still they emit errors, and we don't explain this "expectation", which goes in contract with
> 5. Recommended rules should emit errors
> 6. Rules that are not recommended, should emit warnings

I you meant to also change how `nursery` rules are created and their process, then **please** make sure to state these changes on the **website**. My concerns are not around the changes of the PR, but the fact that changes are "mixed" (technical and not) and the fact that the non-technical changes of this PR aren't reflected on the website (apart form the auto-generated parts).

**Comment by leops** [comment]
@ematipico Just to make sure I understand correctly, the changes you're proposing to the website would be:
- Explicitly document the current behavior that recommended rules emit errors by default while non-recommended rules emit warnings
- Document a specific exception to this for nursery rules on nightly builds, as they are unstable and may emit diagnostics with any severity by default depending on whether we intend for them to be recommended or not on stabilization

**Comment by ematipico** [comment]
> @ematipico Just to make sure I understand correctly, the changes you're proposing to the website would be:
> 
>     * Explicitly document the current behavior that recommended rules emit errors by default while non-recommended rules emit warnings
> 
>     * Document a specific exception to this for nursery rules on nightly builds, as they are unstable and may emit diagnostics with any severity by default depending on whether we intend for them to be recommended or not on stabilization

And explain why `nursery` rules that shows are "not recommended" have `Error` in their diagnostics/examples.

**Review by ematipico — APPROVED** [review]

**Pull request merged**
