### PR TITLE
feat(rome_js_analyzer): promote nursery rules

### PR DESCRIPTION
**Pull request by ematipico**
## Summary

This PR aims to promote the `nursery` rules that were shipped since `11.0.0` version. Here's a breakdown of the changes:

### `suspicious`

- `noEmptyInterface`
- `noExtraNonNullAssertion`
- `noRedundantUseStrict`
- `noConstEnum`
- `useDefaultSwitchClauseLast`

### `correctness`

- `noUnsafeFinally`
- `noDuplicateObjectKeys`
- `noConstructorReturn`
- `noPrecisionLoss`
- `noVoidTypeReturn`
- `noStringCaseMismatch`
- `noSetterReturn`

### `style`

- `useExponentiationOperator`
- `useNumericLiterals`
- `useDefaultParameterLast`
- `useConst`
- `noVar`
- `useEnumInitializers`
- `noNonNullAssertion`

### `a11y`

- `noDistractingElements`
- `noHeaderScope`
- `noAccessKey`

### `complexity`

- `useSimplifiedLogicExpression` not recommended

## Open questions

Rules `noVar` and `useConst` are a bit controversial. I needed to figure out where to put them.
They don't catch any bug, so `correctness`. People can use `var` all over their code base, which should be fine.

I don't want Rome to get in the way of developers too much. 

I am happy to have some feedback and ear opinions!

## Test Plan

CI should pass

## Documentation

Not needed, everything is autogenerated.

### CODE REVIEW

**Comment by Conaclos** [comment]
Some suggestions:

- Because `noDuplicateParameters` is in **suspicious**, I think that `noDuplicateObjectKeys` should also be in **suspicious**.

- Because `noExtraNonNullAssertion` is part of **suspicious**, we could move `noNonNullAssertion` in **style**.

- I could move `noSetterReturn` to **correctness**.

- In contrast, I could move `noConstructorReturn` to **suspicious** because there are [non-idiomatic use of return in a constructor](https://github.com/rome/tools/issues/4005).

- I could move `useEnumInitializers` and `noConstEnum` to **style**.

> Rules noVar and useConst are a bit controversial. I needed to figure out where to put them.
> They don't catch any bug, so correctness. People can use var all over their code base, which should be fine.

I think **style** is a good place for them :)

> I don't want Rome to get in the way of developers too much.

This means that these rules are not in **recommended**?

By the way, I am wondering if we should un-promote some rules that are known as unstable (i.e. move them to **nursery**). I am thinking about `useOptionalChain` #4145 and `useSimplifiedLogicExpression` #4163.

**Comment by Conaclos** [comment]
Regarding `noVar` and `useConst`, I am wondering if we should introduce a kind of **strict** mode that supersedes **recommended**. This is the approach taken by [ESlint TypeScript](https://typescript-eslint.io/rules/) to provide more opinionated rules.

**Comment by ematipico** [comment]
@Conaclos Thank you for all your suggestions! They all make sense! Here some question for you:

> I could move `useEnumInitializers` and `noConstEnum` to style.

Any particular reason why? It makes sense for `useEnumInitializers`, but `noConstEnum` has a description that makes me think "OK, maybe something could go wrong...". 

> This means that these rules are not in recommended?

They **are recommended**. They just go under a category that forces how to style your code.

> By the way, I am wondering if we should un-promote some rules that are known as unstable (i.e. move them to nursery). I am thinking about useOptionalChain https://github.com/rome/tools/issues/4145 and useSimplifiedLogicExpression https://github.com/rome/tools/issues/4163.

- `useSimplifiedLogicExpression` => we could **not** recommend it;
- `useOptionalChain` => I am not sure about it... it's a useful rule, and people could turn it off via comment if they need; 🤔

**Comment by Conaclos** [comment]
> noConstEnum has a description that makes me think "OK, maybe something could go wrong...".

You are right. Let's keep it in **suspicious**.

> useOptionalChain => I am not sure about it... it's a useful rule, and people could turn it off via comment if they need; thinking

I think it is a good rule to have and to recommend. I proposed to temporary move the rule to **nursery** because of the reported issues. Another solution could be to fix most of its issues before the release. Not sure how to proceed...

**Comment by ematipico** [comment]
Yeah, let's see if we can flash out a fix for it. I think it's worth it!

**Comment by ematipico** [comment]
I will merge it; if you have any concerns or proposals, feel free to comment or open a PR to update the promotion of the rules.

**Pull request merged**
