### PR TITLE
feat(css-prefix): add shape support

### PR DESCRIPTION
**Pull request by sergeypriakhin**
## Summary

This PR adds support to the shape property. Issue [#1423](https://github.com/rome/tools/issues/1423)

## Test Plan

./rome ci
checked the prefixes https://autoprefixer.github.io/

### CODE REVIEW

**Comment by ematipico** [comment]
Thank you! Can you please rebase and run `./script generate-all-files`?

**Comment by sergeypriakhin** [comment]
> Thank you! Can you please rebase and run `./script generate-all-files`?

yes, i do it

**Comment by ematipico** [comment]
Sorry @sergeypriakhin , could you please do it again? I merged another PR and that generated the conflict

**Comment by ematipico** [comment]
@sergeypriakhin  I think something went wrong with the branch. Also, the conflict hasn't been fixed

**Comment by ematipico** [comment]
@sergeypriakhin probably you didn't run `./script generate-all-file` again, that's why there's still the conflict

**Comment by ematipico** [comment]
Thank you!

**Pull request merged**
