### PR TITLE
chore(rome_js_anlayze): split test case of `useOptionalChain` into multiple parts

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
## Summary
1. Split test cases of useOptionalChain into multiple parts to make test running parallel
**Before**
image
**After**
image

## Test Plan
1. CI should pass.

### CODE REVIEW

**Comment by ematipico** [comment]
What logic did you use to split the tests? Because adding number didn't help me to understand if there was some logic behind it

**Comment by IWANABETHATGUY** [comment]
> Did you use some logic to split the tests? Because adding numbers didn't help me to understand if there was some logic behind it.



> Did you use some logic to split the tests? Because adding numbers didn't help me to understand if there was some logic behind it.

There are about 100+ types of tests. Do you think that is a good way to split?

**Comment by IWANABETHATGUY** [comment]
> > > Did you use some logic to split the tests? Because adding numbers didn't help me to understand if there was some logic behind it.
> > 
> > 
> > > Did you use some logic to split the tests? Because adding numbers didn't help me to understand if there was some logic behind it.
> > 
> > 
> > There are about 100+ types of tests. Do you think that is a good way to split?
> 
> I think it's fine, I was only curious how you split the tests. Could you add numbers to **all** files and rebase the branch? There are conflicts

Will reopen another pr, it is hard to rebase now.

**Comment by IWANABETHATGUY** [comment]
Reopen here https://github.com/rome/tools/pull/3312

**Pull request closed without merging**
