### PR TITLE
Update GitHub Actions version

### PR DESCRIPTION
**Pull request by Gumichocopengin8**
## Summary

Update `actions/xxxxx@vx` to `actions/xxxxxx@v3 or 6` since Node12 will be out of life after Aril 30, 2022 [[Reference](https://nodejs.org/en/about/releases/)].  
`actions/xxxx@v3` or `actions/xxxx@v6`  use Node16 whose support lasts until April 30, 2024.

## Test Plan

Check if GitHub Actions workflows work well

### CODE REVIEW

**Comment by Gumichocopengin8** [comment]
Hello @ematipico,
Could you manually run the GitHub Actions to test this change?

**Comment by Gumichocopengin8** [comment]
I couldn't see the GitHub Actions running at first but it was just invisible.
Could somebody run this flow again? I think the error, `AWS_S3_BUCKET is not set. Quitting.` comes from somewhere else. https://github.com/jakejarvis/s3-sync-action/issues/53

**Comment by NicholasLYang** [comment]
Appears to be a permissions issue. I'll see if we can fix that. But agreed, it shouldn't be a blocker for this PR

**Comment by Gumichocopengin8** [comment]
@NicholasLYang Thanks

**Review by MichaReiser — APPROVED** [review]
Thanks!

**Pull request merged**
