### PR TITLE
chore: Upgrade to Rust 1.65.0

### PR DESCRIPTION
**Pull request by MichaReiser**
## Summary

Updates Rome to use [Rust 1.65.0](https://blog.rust-lang.org/2022/11/03/Rust-1.65.0.html#let-else-statements)

## Test Plan

`cargo test`

### CODE REVIEW

**Comment by MichaReiser** [comment]
!bench_formatter

**Comment by MichaReiser** [comment]
!bench_parser

**Comment by MichaReiser** [comment]
@leops is https://doc.rust-lang.org/stable/std/backtrace/struct.Backtrace.html something we may want to use for our diagnostics?

**Comment by MichaReiser** [comment]
@leops is https://doc.rust-lang.org/stable/std/backtrace/struct.Backtrace.html something we may want to use for our diagnostics?

**Comment by leops** [comment]
> @leops is https://doc.rust-lang.org/stable/std/backtrace/struct.Backtrace.html something we may want to use for our diagnostics?

Not at the moment since the `Backtrace` type in the standard library does not expose a stable API to inspect the frames of the backtrace yet (which is used to customize how backtraces are printed as markup, filter out irrelevant frames and enable the backtraces to be serialized), so we still have to rely on the `backtrace` crate for now

**Review by leops — APPROVED** [review]

**Pull request merged**
