### PR TITLE
feat(xtask): Generate detailed coverage report for xtask compare

### PR DESCRIPTION
**Pull request by Boshen**
## Summary
This implements detailed coverage report for xtask compare, reporting better diffs, see #1844

## Test Plan
```
cargo xtask coverage --json > base_results.json 
```
Break the parser (comment some random code out), then
```
cargo xtask coverage --json > new_results.json
cargo xtask compare ./base_results.json ./new_results.json  --markdown
```

### CODE REVIEW

**Comment by Boshen** [comment]
Example output: 

| Test result | `main` count | This PR count | Difference |
| :---------: | :----------: | :-----------: | :--------: |
| Total | 17608 | 17608 | 0 |
| Passed | 17084 | 17036 | ❌ ⏬ **-48** |
| Failed | 523 | 571 | ❌ ⏫ **+48** |
| Panics | 1 | 1 | 0 |
| Coverage | 97.02% | 96.75% | **-0.27%** |

<details><summary><b>:fire: Regression (14):</b></summary>

```
xtask/src/coverage/test262/test/language/expressions/async-function/early-errors-expression-NSPL-with-USD.js
xtask/src/coverage/test262/test/language/expressions/async-function/early-errors-expression-body-contains-super-property.js
xtask/src/coverage/test262/test/language/expressions/async-function/early-errors-expression-formals-body-duplicate.js
xtask/src/coverage/test262/test/language/expressions/async-function/early-errors-expression-formals-contains-super-property.js
xtask/src/coverage/test262/test/language/expressions/await/await-BindingIdentifier-nested.js
xtask/src/coverage/test262/test/language/module-code/early-dup-top-function-async-generator.js
xtask/src/coverage/test262/test/language/module-code/early-dup-top-function-async.js
xtask/src/coverage/test262/test/language/module-code/export-default-asyncfunction-declaration-binding-exists.js
xtask/src/coverage/test262/test/language/module-code/export-default-asyncgenerator-declaration-binding-exists.js
xtask/src/coverage/test262/test/language/statements/async-function/early-errors-declaration-NSPL-with-USD.js
xtask/src/coverage/test262/test/language/statements/async-function/early-errors-declaration-body-contains-super-property.js
xtask/src/coverage/test262/test/language/statements/async-function/early-errors-declaration-duplicate-parameters.js
xtask/src/coverage/test262/test/language/statements/async-function/early-errors-declaration-formals-body-duplicate.js
xtask/src/coverage/test262/test/language/statements/async-function/early-errors-declaration-formals-contains-super-property.js
```
</details>

<details><summary><b>:tada: Fixed (62):</b></summary>

```
xtask/src/coverage/test262/test/built-ins/AsyncFunction/AsyncFunction-construct.js
xtask/src/coverage/test262/test/built-ins/AsyncFunction/AsyncFunction-is-extensible.js
xtask/src/coverage/test262/test/built-ins/AsyncFunction/AsyncFunction-is-subclass.js
xtask/src/coverage/test262/test/built-ins/AsyncFunction/AsyncFunction-length.js
xtask/src/coverage/test262/test/built-ins/AsyncFunction/AsyncFunction-name.js
xtask/src/coverage/test262/test/built-ins/AsyncFunction/AsyncFunction-prototype.js
xtask/src/coverage/test262/test/built-ins/AsyncFunction/AsyncFunction.js
xtask/src/coverage/test262/test/built-ins/AsyncFunction/AsyncFunctionPrototype-is-extensible.js
xtask/src/coverage/test262/test/built-ins/AsyncFunction/AsyncFunctionPrototype-prototype.js
xtask/src/coverage/test262/test/built-ins/AsyncFunction/instance-construct-throws.js
xtask/src/coverage/test262/test/built-ins/AsyncFunction/instance-has-name.js
xtask/src/coverage/test262/test/built-ins/AsyncFunction/instance-length.js
xtask/src/coverage/test262/test/built-ins/AsyncFunction/instance-prototype-property.js
xtask/src/coverage/test262/test/built-ins/Object/seal/seal-asyncfunction.js
xtask/src/coverage/test262/test/built-ins/Object/seal/seal-asyncgeneratorfunction.js
xtask/src/coverage/test262/test/language/expressions/async-function/expression-returns-promise.js
xtask/src/coverage/test262/test/language/expressions/async-function/name.js
xtask/src/coverage/test262/test/language/expressions/async-function/syntax-expression-is-PrimaryExpression.js
xtask/src/coverage/test262/test/language/expressions/async-function/try-reject-finally-reject.js
xtask/src/coverage/test262/test/language/expressions/async-function/try-reject-finally-return.js
xtask/src/coverage/test262/test/language/expressions/async-function/try-reject-finally-throw.js
xtask/src/coverage/test262/test/language/expressions/async-function/try-return-finally-reject.js
xtask/src/coverage/test262/test/language/expressions/async-function/try-return-finally-return.js
xtask/src/coverage/test262/test/language/expressions/async-function/try-return-finally-throw.js
xtask/src/coverage/test262/test/language/expressions/async-function/try-throw-finally-reject.js
xtask/src/coverage/test262/test/language/expressions/async-function/try-throw-finally-return.js
xtask/src/coverage/test262/test/language/expressions/async-function/try-throw-finally-throw.js
xtask/src/coverage/test262/test/language/expressions/async-generator/name.js
xtask/src/coverage/test262/test/language/expressions/await/await-awaits-thenable-not-callable.js
xtask/src/coverage/test262/test/language/expressions/await/await-awaits-thenables-that-throw.js
xtask/src/coverage/test262/test/language/expressions/await/await-awaits-thenables.js
xtask/src/coverage/test262/test/language/expressions/await/await-in-nested-function.js
xtask/src/coverage/test262/test/language/expressions/await/await-throws-rejections.js
xtask/src/coverage/test262/test/language/expressions/await/syntax-await-has-UnaryExpression-with-MultiplicativeExpression.js
xtask/src/coverage/test262/test/language/expressions/await/syntax-await-has-UnaryExpression.js
xtask/src/coverage/test262/test/language/module-code/export-default-asyncfunction-declaration-binding.js
xtask/src/coverage/test262/test/language/module-code/export-default-asyncgenerator-declaration-binding.js
xtask/src/coverage/test262/test/language/statements/async-function/declaration-returns-promise.js
xtask/src/coverage/test262/test/language/statements/async-function/evaluation-body-that-returns-after-await.js
xtask/src/coverage/test262/test/language/statements/async-function/evaluation-body-that-returns.js
xtask/src/coverage/test262/test/language/statements/async-function/evaluation-body-that-throws-after-await.js
xtask/src/coverage/test262/test/language/statements/async-function/evaluation-body-that-throws.js
xtask/src/coverage/test262/test/language/statements/async-function/evaluation-body.js
xtask/src/coverage/test262/test/language/statements/async-function/evaluation-default-that-throws.js
xtask/src/coverage/test262/test/language/statements/async-function/evaluation-mapped-arguments.js
xtask/src/coverage/test262/test/language/statements/async-function/evaluation-this-value-global.js
xtask/src/coverage/test262/test/language/statements/async-function/evaluation-this-value-passed.js
xtask/src/coverage/test262/test/language/statements/async-function/evaluation-unmapped-arguments.js
xtask/src/coverage/test262/test/language/statements/async-function/syntax-declaration-line-terminators-allowed.js
xtask/src/coverage/test262/test/language/statements/async-function/syntax-declaration-no-line-terminator.js
xtask/src/coverage/test262/test/language/statements/async-function/syntax-declaration.js
xtask/src/coverage/test262/test/language/statements/async-function/try-reject-finally-reject.js
xtask/src/coverage/test262/test/language/statements/async-function/try-reject-finally-return.js
xtask/src/coverage/test262/test/language/statements/async-function/try-reject-finally-throw.js
xtask/src/coverage/test262/test/language/statements/async-function/try-return-finally-reject.js
xtask/src/coverage/test262/test/language/statements/async-function/try-return-finally-return.js
xtask/src/coverage/test262/test/language/statements/async-function/try-return-finally-throw.js
xtask/src/coverage/test262/test/language/statements/async-function/try-throw-finally-reject.js
xtask/src/coverage/test262/test/language/statements/async-function/try-throw-finally-return.js
xtask/src/coverage/test262/test/language/statements/async-function/try-throw-finally-throw.js
xtask/src/coverage/test262/test/language/statements/switch/scope-lex-async-function.js
xtask/src/coverage/test262/test/language/statements/switch/scope-lex-async-generator.js
```
</details>

**Comment by MichaReiser** [comment]
I love it! Let's wait for the checks to complete

**Comment by Boshen** [comment]
Hold on, the loops are in the wrong order :-/

**Comment by Boshen** [comment]
Fixed, :shipit:

**Comment by ematipico** [comment]
> I now need to work on a new PR where the action can comment

The actions can't comment on PRs opened from forks, remember. We just need to approved and merge it. Or test it locally.

**Review by ematipico — APPROVED** [review]
Much better! Thank you!

**Pull request merged**
