### PR TITLE
feat(css-prefix): text decoration support

### PR DESCRIPTION
**Pull request by grimxreaper**
**Summary**
This PR adds support for the text-decoration CSS property. Issue #1423 

**Test Support**
./rome test

### CODE REVIEW

**Comment by ematipico** [comment]
Hi @grimxreaper , thank you for you PR! Would you mind change the title of your PR? Please follow the suggestions [here](https://github.com/rome/tools/blob/main/CONTRIBUTING.md#creating-pull-requests)

**Comment by grimxreaper** [comment]
> Hi @grimxreaper , thank you for you PR! Would you mind change the title of your PR? Please follow the suggestions [here](https://github.com/rome/tools/blob/main/CONTRIBUTING.md#creating-pull-requests)

All done, I hope this is satisfactory? Thanks!

**Review by ematipico — COMMENTED** [review]
Looks good! Could you rebase your branch, run `./script generate-all-files` and commit the changes?

**Comment by grimxreaper** [comment]
> Looks good! Could you rebase your branch, run `./script generate-all-files` and commit the changes?

I should run `git rebase main` right?  For some reason that brings up 2 conflicts so I just want to make sure.

**Comment by ematipico** [comment]
You should run the following commands:
- `git fetch upstream`
- `git rebase upstream/main`

This will rebase your files based on the latest in `upstream` remote.

Regarding the conflict, doesn't matter which one you choose (you can accept your changes). When you run `./script generate-all-files`, the script will regenerate automatically that file for you.

**Comment by grimxreaper** [comment]
I think that worked, could you see if it is what you expect? @ematipico 

I had to do one more git pull after running the script in order to commit, because: 
`Your branch and 'origin/feat/text-decoration' have diverged,
and have 17 and 2 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)`

Please let me know if I need to do something else? 
I appreciate your help very much! Thank you.

**Comment by ematipico** [comment]
Yes, when you do use the command `rebase`, you have to force push because the history gets rewritten. It's normal. It should be good now! Thank you!

**Comment by grimxreaper** [comment]
Ah okay, great, let me know if I need to do anything else, thank you!

**Comment by jamiebuilds** [comment]
Hi! Thank you so much for your contribution!

We recently made the decision to [migrate the Rome codebase to Rust](https://rome.tools/blog/2021/09/21/rome-will-be-rewritten-in-rust) and making some significant changes to its architecture.

We're going through and closing pull requests and issues that were specific to the TypeScript codebase, including this one. But while we're closing this, we'd love to have your involvement in the future.

Thanks again!

**Pull request closed without merging**
