### PR TITLE
chore: rename rome crates

### PR DESCRIPTION
**Pull request by mrkldshv**
## Summary

Apply `rome_` prefix naming convention for all rome crates as agreed in #1737.

Renamed crates: 
* cli
* core
* formatter
* path

## Test Plan

```
cargo lint
cargo test
```

### CODE REVIEW

**Comment by mrkldshv** [comment]
I wasn't really sure if we should rename `tests_macros` package. Would you suggest keeping it as it is?

**Review by ematipico — APPROVED** [review]
Looks good to me! Thank you!

**Comment by ematipico** [comment]
> I wasn't really sure if we should rename `tests_macros` package. Would you suggest keeping it as it is?

I think we can skip it for now. Probably we could consider to move it somewhere else, later.

**Review by xunilrj — APPROVED** [review]

**Comment by ematipico** [comment]
Thank you @mrkldshv !

**Comment by mrkldshv** [comment]
@ematipico Happy to help! Would be glad to pick up something else.

**Pull request merged**
