### PR TITLE
feat(rome_analyze): useSortedSpecifiers

### LINKED ISSUE #2671: 📎 (rome_analyze): useSortedSpecifiers
### Description

useSortedSpecifiers

https://github.com/rome/tools/blob/archived-js/website/src/docs/lint/rules/js/useSortedSpecifiers.md

### LINKED ISSUE #2755: useSortedSpecifiers
https://github.com/rome/tools/blob/archived-js/website/src/docs/lint/rules/js/useSortedSpecifiers.md

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
## Summary
1. Resolved #2755 

## Test Plan
1. cargo test

### CODE REVIEW

**Comment by ematipico** [comment]
@IWANABETHATGUY any updates on this PR?

**Comment by IWANABETHATGUY** [comment]
> @IWANABETHATGUY any updates on this PR? Do you need any help?

Nope, thanks for reminding me. I will push forward the pr this weekend.

**Comment by ematipico** [comment]
We might have someone from the team to take over it, if we decide to have it in the next release.

**Comment by IWANABETHATGUY** [comment]
> We might have someone from the team to take over it, if we decide to have it in the next release.

feel free to do that.

**Comment by ematipico** [comment]
@leops @xunilrj can any of you guys take over this issue please? It's been open for quite some time. We could prepare this for the next release

**Comment by leops** [comment]
> @leops @xunilrj can any of you guys take over this issue please? It's been open for quite some time. We could prepare this for the next release

I can take a look at it yes

**Pull request closed without merging**
