### PR TITLE
fix(rome_js_formatter): 🐛 preserve new-lines after directives

### LINKED ISSUE #2437: Preserve new-lines after directives
Prettier preserve's any empty line placed between a directive and the first statement, Rome doesn't. [Playground](https://play.rome.tools/?lineWidth=80&indentStyle=space&quoteStyle=double&indentWidth=2&typescript=true&jsx=false&sourceType=module#IgB1AHMAZQAgAHMAdAByAGkAYwB0ACIAOwAKAAoAZgB1AG4AYwB0AGkAbwBuACAAZgAxACgAKQAgAHsACgAgACAAIgB1AHMAZQAgAHMAdAByAGkAYwB0ACIAOwAKAH0ACgAKAGYAdQBuAGMAdABpAG8AbgAgAGYAMgAoACkAIAB7AAoAIAAgACcAbgBnAEkAbgBqAGUAYwB0ACcAOwAKACAAIABPAGIAagBlAGMAdAAuAGEAcwBzAGkAZwBuACgAdABoAGkAcwAsACAAewAgACQAbABvAGcALAAgACQAdQBpAGIATQBvAGQAYQBsACAAfQApADsACgB9AAoACgBmAHUAbgBjAHQAaQBvAG4AIABmADMAKAApACAAewAKAAoAIAAgACcAbgBnAEkAbgBqAGUAYwB0ACcAOwAKAAoAIAAgAE8AYgBqAGUAYwB0AC4AYQBzAHMAaQBnAG4AKAB0AGgAaQBzACwAIAB7ACAAJABsAG8AZwAsACAAJAB1AGkAYgBNAG8AZABhAGwAIAB9ACkAOwAKAAoAfQAKAAoAZgB1AG4AYwB0AGkAbwBuACAAZgA0ACgAKQAgAHsACgAgACAAJwBuAGcASQBuAGoAZQBjAHQAJwA7AAoAIAAgAAoAIAAgACIAdQBzAGUAIABzAHQAcgBpAGMAdAAiAAoACgAKACAAIABPAGIAagBlAGMAdAAuAGEAcwBzAGkAZwBuACgAdABoAGkAcwAsACAAewAgACQAbABvAGcALAAgACQAdQBpAGIATQBvAGQAYQBsACAAfQApADsACgB9AAoA)

## Input

```ts
"use strict";

function f1() {
  "use strict";
}

function f2() {
  'ngInject';
  Object.assign(this, { $log, $uibModal });
}

function f3() {

  'ngInject';

  Object.assign(this, { $log, $uibModal });

}

function f4() {
  'ngInject';
  
  "use strict"


  Object.assign(this, { $log, $uibModal });
}

```

## Prettier

```ts
"use strict";

function f1() {
  "use strict";
}

function f2() {
  "ngInject";
  Object.assign(this, { $log, $uibModal });
}

function f3() {
  "ngInject";

  Object.assign(this, { $log, $uibModal });
}

function f4() {
  "ngInject";

  "use strict";

  Object.assign(this, { $log, $uibModal });
}

```

## Rome

```ts
"use strict";
function f1() {
  "use strict";
}

function f2() {
  "ngInject";
  Object.assign(this, { $log, $uibModal });
}

function f3() {
  "ngInject";
  Object.assign(this, { $log, $uibModal });
}

function f4() {
  "ngInject";

  "use strict";
  Object.assign(this, { $log, $uibModal });
}
```

## Expected
Rome's formatting to match prettier's.

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
## Summary
Fix #2437

## Test Plan
The updated snapshot should fix related issue #2437, 
you could review the snapshot this pr updated.

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
!bench_formatter

**Comment by IWANABETHATGUY** [comment]
It seems that I became a core contributor, 
https://github.com/rome/tools/blob/main/CONTRIBUTING.md#if-you-are-a-core-contributor

**Comment by ematipico** [comment]
> It seems that I became a core contributor, 
> https://github.com/rome/tools/blob/main/CONTRIBUTING.md#if-you-are-a-core-contributor

I think it was a mistake of mine. I didn't know contributors could run bench tests, which is great!

Although compliance tests can't be, that one I know 🤣

**Review by ematipico — APPROVED** [review]
Thank you for your contribution!

**Pull request merged**
