### PR TITLE
feat(rome_js_analyzer): `noConsoleLog` rule

### LINKED ISSUE #4223: 📎 `noConsoleLog`
### Description

https://eslint.org/docs/latest/rules/no-console

forces people to use .error, .info, but not .log as it's for debug purposes and not explicit about the context of the output.

Or maybe it's better to have a more general purpose 'ban', so users can configure more fine-grained things to ban including something like this.

### PR DESCRIPTION
**Pull request by ematipico**
## Summary

Implements the rule `noConsoleLog`.

Closes #4223

This rule prevents the usage of `console.log`, while all the other functions from `console` are allowed.

## Test Plan

Added tests

## Changelog

- [x] The PR requires a changelog line

## Documentation

- [x] The PR requires documentation
- [ ] I will create a new PR to update the documentation

### CODE REVIEW

**Review by Conaclos — COMMENTED** [review]
It could be nice to add other valid codes such as: 

```js
console.info("info")
console.warn("warn")
console.error("error")
console.assert(true)
```

**Comment by ematipico** [comment]
> It could be nice to add other valid codes such as:
> 
> ```js
> console.info("info")
> console.warn("warn")
> console.error("error")
> console.assert(true)
> ```

Where precisely? In the test suite or the documentation?

**Comment by jpike88** [comment]
Yesssss you guys are absolute machines

**Comment by jfmengels** [comment]
I'm curious (but I don't need it): Is there a reason that things like `globalThis.console.log()` are not reported in this implementation?

**Comment by ematipico** [comment]
Uncaught case from my side :)

Although all the rules don't take that into consideration, probably because most of the users (myself in primis) don't use it, so it was missed.

**Comment by jfmengels** [comment]
I don't use it either, but it's an easy workaround to the rule.
I'm actually surprised that some of the rules do, nice :+1:
ESLint doesn't seem to be handling this, I guess partially because `globalThis` is somewhat new?
(Also, just in case you will be tackling it, apparently `globalThis.globalThis.globalThis.console.log(1)` is possible :upside_down_face: )

**Pull request merged**
