### PR TITLE
fix: documentation #1214

### LINKED ISSUE #1214: 🐛 Little problem with the "preferOptionalChaining" documentation
I just wanted to report that the doc page of the "preferOptionalChaining" rule, on the website, is the raw markdown: https://rome.tools/docs/lint/rules/js/preferoptionalchaining/

### PR DESCRIPTION
**Pull request by aravind1078**
## Summary

this PR fixes the website documentation for preferOptionalChaining lint rule

closes #1214

### CODE REVIEW

**Review by ematipico — APPROVED** [review]
Thank you!

**Comment by darthmaim** [comment]
I wonder if this could have been prevented with a linting rule detecting indented frontmatter. Differentiating wrongly indented frontmatter from a codeblock (created by indentation instead of ` ``` `) starting with `---` is difficult though. Is there a linting rule prefering ` ``` ` over indentation for codeblocks?

**Comment by ematipico** [comment]
We don't have a markdow linter yet but it's surely something that we can thing about.

Although, about the bad formatting (tab) of what happened here inside the `---` block, it's not something that we can lint, I think. It's not part of the spec and it's something particularly tailored for 11ty (to be more specific, the package `gray-matter`)

**Comment by darthmaim** [comment]
Even though Frontmatter is not in the spec, it's not something specific to 11ty. Most static site generators use it and even github has support for rendering it.

**Comment by ematipico** [comment]
Github supports it? Really? 😮  I think I didn't understand the frontmatter part.

Anyway, it's surely something that we can have once we have a working parser!

**Comment by darthmaim** [comment]
Yes, this is how github renders it (see for example https://github.com/rome/tools/blob/main/website/src/docs/lint/rules/js/preferOptionalChaining.md):

image

I have added a comment to #985 about frontmatter.

**Pull request merged**
