### PR TITLE
fix(rome_cli): better printing of message

### PR DESCRIPTION
**Pull request by ematipico**
## Summary

This PR fixes the printing of a message and it sets the limit of printable diagnostics to a higher limit

## Test Plan

Screenshot 2022-07-26 at 08 08 23

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
https://github.com/rome/tools/pull/2929/files#diff-fb912ee1fd0e24af6fd125034ed4321c2d09d098bc73a8b93bb5895dbe2fc639R27 
You should change this line to 200 as well

**Comment by IWANABETHATGUY** [comment]
What if I want to show all the diagnostics? How could I do that?

**Comment by Boshen** [comment]
Does this fixes the problem where it keeps printing "The number of diagnostics exceeds the number allowed by Rome."? The actual diagnostics will get cleared away. I'm expecting the message to only display once.

**Comment by ematipico** [comment]
> Does this fixes the problem where it keeps printing "The number of diagnostics exceeds the number allowed by Rome."? The actual diagnostics will get cleared away. I'm expecting the message to only display once.

I don't know, it would be great to be able to reproduce the issue somehow

**Comment by leops** [comment]
> > Does this fixes the problem where it keeps printing "The number of diagnostics exceeds the number allowed by Rome."? The actual diagnostics will get cleared away. I'm expecting the message to only display once.
> 
> I don't know, it would be great to be able to reproduce the issue somehow

My guess is that this issue is cause by the line that prints the "diagnostics not shown" message being inside of the receiver loop, this will cause it to be printed again for every file that gets checked

> What if I want to show all the diagnostics? How could I do that?

I think at the moment this isn't allowed since we haven't seen any value to showing more than 200 diagnostics, it just seems like a lot of noise. Of course if there's a compelling enough use case to include this feature we could consider it

**Review by leops — APPROVED** [review]

**Pull request merged**
