### PR TITLE
chore(coverage): better panic log for coverage

### PR DESCRIPTION
**Pull request by xunilrj**
This PR improve log to help tackle some flaky tests for ```coverage --suites=symbols```.

The error messages I am seeing do not help. In one case we are seeing an out-of-bounds indexing that should not happen. I can't seem to be able to reproduce this locally.

```
byte index 2735 is out of bounds of `// @strictNullChecks: true\r\n\r\n// Repro from #8513\r\n\r\nlet cond: boolean;\r\n\r\nexport type Optional<a> = Some<a> | None;\r\n\r\nexport interface None { readonly none: string; }\r\nexport interface Some<a> { readonly some: a; }\r\n\r\nexport const none : None = { none: '`[...]
```

I have also cleaned the current tests panicking. Not they are failing. To remove some noise.

We generate two error messages when a test fail:

```
2022-06-07T14:48:40.476399Z ERROR xtask_coverage::runner: Test panicked panic="panicked at 'byte index 999999999 is out of bounds of `...`, library\\core\\src\\str\\mod.rs:107:9" stacktrace="xtask\\coverage\\src\\runner.rs @ line 239\nxtask\\coverage\\src\\symbols\\msts.rs @ line 82\nxtask\\coverage\\src\\symbols\\msts.rs @ line 75\nxtask\\coverage\\src\\runner.rs @ line 311\nxtask\\coverage\\src\\runner.rs @ line 311\nBaseThreadInitThunk\nRtlUserThreadStart\n"
2022-06-07T14:48:40.477396Z ERROR xtask_coverage::runner: Test panicked panic="byte index 999999999 is out of bounds of `...`" name=wrappedAndRecursiveConstraints3.symbols
```

The first comes from ```std::panic::set_hook```and the second from ```std::panic::catch_unwind```. The major issue that demands two is that ```catch_unwind```do not have the ```PanicInfo``` struct the gives me access to the stacktrace.

And give nthat we run multiple tests in parallel, inside ```set_hook``` is very hard for me to correlate which test panicked.

#### backtrace-rs

I chose this lib (https://github.com/rust-lang/backtrace-rs) because the standard backtrace is not stable yet (https://doc.rust-lang.org/std/backtrace/index.html)

#### release-with-debug

To be able to see a meaningful backtrace we need debug info even on release builds. I created a new profile to not affect the release binary.

My honest opinion is that we also need this for production, but we can decide on this later.

### CODE REVIEW

**Comment by ematipico** [comment]
How can we see the effect of these changes on this PR? I can't seem to see anything in the actions triggered by the PR

**Comment by xunilrj** [comment]
> How can we see the effect of these changes on this PR? I can't seem to see anything in the actions triggered by the PR

You can search for "test panicked"

image

**Comment by ematipico** [comment]
Thank you!

**Review by ematipico — APPROVED** [review]

**Comment by MichaReiser** [comment]
My guess on which test is panicking from looking at the string you pasted is 

https://github.com/microsoft/Typescript/blob/4fdc4fd6b6d744ff7953c1229b04ea915790d8ca/tests/cases/conformance/controlFlow/typeGuardsAsAssertions.ts#L3

**Pull request merged**
