### PR TITLE
feat(cli): add `suppressLogs` flag for `rome test`

### PR DESCRIPTION
**Pull request by UsamaHameed**
## Summary

This PR adds support for `--no-suppress-logs` flag for `rome test` so that logs can be viewed in all cases.

Thanks to @sebmck for the help.

## Test Plan

`./rome ci`
`./rome test`
`./rome test --no-suppress-logs`

### CODE REVIEW

**Review by ematipico — CHANGES_REQUESTED** [review]
We need to add this new flag to the list of acceptable flags via CLI: https://github.com/rome/tools/blob/main/internal/core/server/commands/test.ts#L27-L34

**Comment by ematipico** [comment]
We have missing description and we should start adding them. To add a description to a command:

```js
	defineFlags(c) {
		return {
			newFlag: c.get(
				"newFlag",
				{
					description: markup`I am an amazing flag.`,
				},
			).asBoolean(false),
		};
	},
```

**Comment by UsamaHameed** [comment]
@ematipico Its already added to the commands here: https://github.com/rome/tools/pull/1462/files#diff-f5405c56556df74de15fa60a011be6d78f1e5910b9d33b64fe4ed0d3a3d77e48R37 
As for the descriptions for this and the others, I can add them in this PR 👍

**Comment by ematipico** [comment]
> @ematipico Its already added to the commands here: [#1462 (files)](https://github.com/rome/tools/pull/1462/files#diff-f5405c56556df74de15fa60a011be6d78f1e5910b9d33b64fe4ed0d3a3d77e48R37)
> As for the descriptions for this and the others, I can add them in this PR 👍

Sorry, I must have missed it!

Could you add the description to this new flag, please?

**Comment by UsamaHameed** [comment]
@ematipico done. I have added descriptions for all the cli options for `rome test`

**Pull request merged**
