### PR TITLE
fix(rome_js_parser):🐛 issue_2790

### LINKED ISSUE #2790: 🐛 Incorrect parsing of mapped types
### Environment information

```bash
Latest version on `main`
```

### What happened?

Rome fails to parse the following snippet:

```ts
var x: {
  [A in keyof B]?: any;
 };
```

[Playground](https://play.rome.tools/94bc262/?lineWidth=80&indentStyle=tab&quoteStyle=double&indentWidth=2&sourceType=module&treeStyle=1&typescript=true&jsx=true#dgBhAHIAIAB4ADoAIAB7AAoACgAKAAoAIAAgAFsAQQAgAGkAbgAgAGsAZQB5AG8AZgAgAEIAXQA/ADoAIABhAG4AeQA7AAoACgAgAH0AOwA=)

There aren't any diagnostics, but there's a missing token which is required, which is the `operator_token`.

Well, it should be required: https://www.typescriptlang.org/play?#code/G4QwTgBAHgXBDeAoZiIQNoEEIEsB2EA1gKYCeA9gGYQBCAugPxwh6kDcyEAvm0A

### Expected result

It should not emit any syntax errors.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
### main

**File Based Average Prettier Similarity**: 76.34%  
**Line Based Average Prettier Similarity**: 71.91%  

### pr
**File Based Average Prettier Similarity**: 76.41%  
**Line Based Average Prettier Similarity**: 71.93%

## Summary
1. change `operator_token` of `TsMappedTypeOptionalModifierClause` to `optional` 
2. Fixed #2790

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
> 

No, I will change it.

**Comment by IWANABETHATGUY** [comment]
I found that this pr also improves the prettier compatibility a little bit

**Comment by ematipico** [comment]
> I found that this pr also improves the prettier compatibility a little bit

That's how I found the bug 😝

**Review by ematipico — APPROVED** [review]
Thank you!

**Pull request merged**
