### PR TITLE
refactor: use `std::sync::Mutex` instead of `parking_lot::Mutex`

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
## Summary
1. Part of #3054 
2.  With the standard library Mutex and RwLock being const-constructible it's now possible to use these in the DiffReport of the Prettier test suite

## Test Plan
1. Passing CI

### CODE REVIEW

**Review by ematipico — COMMENTED** [review]
Another change that should be part of this PR is removing `lazy_static` around the definition of `METRICS`. 

Now that `Mutex` can be defined as `const`, the usage of `lazy_static` is not needed anymore.

**Comment by IWANABETHATGUY** [comment]
> 

Seems not, `rustc` doesn't allow us to create a const `Mutex` that inner value can't create in compile time.
rustc emit errors below: 
```
cannot call non-const fn `HashMap::<CallsiteKey, Mutex<CallsiteEntry>>::new` in constants
calls in constants are limited to constant functions, tuple structs and tuple variants
```

**Comment by xunilrj** [comment]
!bench_analyzer

**Comment by xunilrj** [comment]
!bench_formatter

**Comment by ematipico** [comment]
> > 
> 
> Seems not, `rustc` doesn't allow us to create a const `Mutex` that inner value can't create in compile time. rustc emit errors below:
> 
> ```
> cannot call non-const fn `HashMap::<CallsiteKey, Mutex<CallsiteEntry>>::new` in constants
> calls in constants are limited to constant functions, tuple structs and tuple variants
> ```

Really difficult to give feedback without seeing the code, but removing only `lazy_static` is not correct, we have to do some refactor.

**Comment by IWANABETHATGUY** [comment]
> pile time. rustc emit errors below:

image

**Comment by IWANABETHATGUY** [comment]
The only way I know to create a hashmap in compile time is `phf`

**Comment by MichaReiser** [comment]
> > > 
> > 
> > 
> > Seems not, `rustc` doesn't allow us to create a const `Mutex` that inner value can't create in compile time. rustc emit errors below:
> > ```
> > cannot call non-const fn `HashMap::<CallsiteKey, Mutex<CallsiteEntry>>::new` in constants
> > calls in constants are limited to constant functions, tuple structs and tuple variants
> > ```
> 
> Really difficult to give feedback without seeing the code, but removing only `lazy_static` is not correct, we have to do some refactor.

The problem is that `RwLock` stores a `HashMap` and `HashMap::new` is not `const`. So you can write `RwLock::new(...)` but there's no way to create the map.

**Review by MichaReiser — APPROVED** [review]

**Pull request merged**
