### PR TITLE
ci: run benchmark with comment containing `!bench`

### PR DESCRIPTION
**Pull request by Boshen**
## Summary
Run benchmark with a comment with text containing `+bench`, a new result will be commented at the bottom of this PR (not updating the existing comment, so its easier to compare things / find the benchmark pr). 

I have moved the file, and fixed the formatting.

### CODE REVIEW

**Comment by Boshen** [comment]
+bench

**Comment by Boshen** [comment]
+bench

**Comment by Boshen** [comment]
+bench why you no bench ??

**Comment by ematipico** [comment]
That's because github doesn't run these kind of jobs from a fork. Only from direct new branches, which can only be open from a core contributor. This is a security restriction set by github.

**Comment by ematipico** [comment]
Is having `+` a pattern? If not, I'd prefer to have `!bench`

**Comment by MichaReiser** [comment]
Should we go ahead and merge it and test it on some other PR?

**Comment by Boshen** [comment]
Ok I've tested this in another repo, this file needs to be in main first.

**Comment by Boshen** [comment]
`!bench` sounds good, updated.

**Review by ematipico — APPROVED** [review]

**Pull request merged**
