### PR TITLE
feat: 🎸 allow comments in json file

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
## Changelog

- [ ] The PR requires a changelog line

## Documentation

- [ ] The PR requires documentation
- [ ] I will create a new PR to update the documentation

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
https://github.com/IWANABETHATGUY/tools/blob/ab690e1f6e9877c2c17a330095faf4e9b2a13892/crates/rome_service/src/file_handlers/javascript.rs#L63-L66, @ematipico sorry for the ping, I am stuck now, I want to pass the `JsonConfiguration.allow_comments` to LanguageSettings, but `Language` trait now is hard to pass language-specific feature, like `allowComments`  options, would you mind I modify the trait and add another associated field `allow_comments` ?

**Comment by ematipico** [comment]
> [IWANABETHATGUY/tools@`ab690e1`/crates/rome_service/src/settings.rs#L198-L207](https://github.com/IWANABETHATGUY/tools/blob/ab690e1f6e9877c2c17a330095faf4e9b2a13892/crates/rome_service/src/settings.rs#L198-L207), @ematipico sorry for the ping, I am stuck now, I want to pass the `JsonConfiguration.allow_comments` to LanguageSettings, but `Language` trait now is hard to pass language-specific feature, like `allowComments` options, would you mind I modify the trait and add another associated field `allow_comments` ?

Sure, it makes sense!

Since each language section is divided by "tool", I think here we should do the same have something like this:

```json
{
	"json": {
		"parser": {
			"allowComments": true
		}
	}
}
```

What do you think?

**Comment by ematipico** [comment]
@IWANABETHATGUY are there any updates? do you need any help?

**Comment by ematipico** [comment]
Closing in favour of https://github.com/rome/tools/pull/4714

**Pull request closed without merging**
