### PR TITLE
refactor(rome_js_analyze): reorganize lint rules into additional categories

### PR DESCRIPTION
**Pull request by leops**
## Summary

Closes https://github.com/rome/tools/issues/3719

This PR introduces new rule groups inspired by Clippy, and changes the group and recommended flag for a number of lint rules in preparation for v11.

### Perf

> Rules catching ways your code could be written to run faster, or generally be more efficient.

The following rules have been moved to this group:
- `noDelete`

### Suspicious

> Rules that detect code that is likely to be incorrect or useless

The following rules have been moved to this group:
- `noArrayIndexKey`
- `noAsyncPromiseExecutor`
- `noCatchAssign`
- `noCommentText`
- `noCompareNegZero`
- `noDebugger`
- `noDoubleEquals`
- `noDupeArgs`
- `noExplicitAny` (+recommended)
- `noFunctionAssign`
- `noImportAssign`
- `noLabelVar`
- `noShadowRestrictedNames`
- `noSparseArray`
- `noUnsafeNegation`
- `useValidTypeof`

### Complexity

The following rules have been moved to this group:
- `noMultipleSpacesInRegularExpressionLiterals`
- `noUselessFragments`
- `useFlatMap` (+recommended)
- `useOptionalChain`

### Correctness

The description of this group has been changed to only include rules that are strict about catching actual errors or dead code, while rules that only detect patterns that might be erroneous have been moved to the `suspicious` group.

The following rules have been moved to this group:
- `noConstAssign` (+recommended)
- `useValidForDirection` (+recommended)

### Nursery

The `noRestrictedGlobals` rule has been downgraded to the `nursery` group as it only seems to be useful if it can be configured by the user, but it doesn't expose a way to specify this configuration yet.

The `recommended` flag has been removed for the `noAccessKey` since it's not stable yet.

### Style

The following rules have been moved to this group:
- `noArguments`
- `useSingleCaseStatement`
- `useWhile`

The following rules are no longer recommended:
- `noImplicitBoolean`
- `noNegationElse`
- `noShoutyConstants`
- `useBlockStatements`
- `useShorthandArrayType`
- `useSingleCaseStatement`

## Test Plan

Besides moving a number of snapshot tests around, I had to change a few tests that relied on the specific group of a rule or category of a diagnostic.

### CODE REVIEW

**Comment by Conaclos** [comment]
I am wondering if `noArguments` is really a stylistic rule. *Complexity* could be a better fit?

**Comment by leops** [comment]
> I am wondering if `noArguments` is really a stylistic rule. _Complexity_ could be a better fit?

It comes down to the definition of each group: `complexity` is for code that code be written in a simpler way, while `style` is for code that could be written in a more idiomatic way. The different between the two is really subtle in this case, but I think it's a slightly better fit for `style`

**Comment by ematipico** [comment]
The `Perf` group should be called `Performance`. Abbreviations should be avoided whenever is possible.

**Comment by Conaclos** [comment]
> The Perf group should be called Performance. Abbreviations should be avoided whenever possible.

I am wondering if several rules should follow the same path:

[noDupeArgs](https://docs.rome.tools/lint/rules/noDupeArgs) -> noDuplicatedFunctionParameters
[noDupeKeys](https://docs.rome.tools/lint/rules/noDupeKeys) -> noDuplicatedObjectKeys

**Comment by jeysal** [comment]
> [noDupeArgs](https://docs.rome.tools/lint/rules/noDupeArgs) -> noDuplicatedFunctionParameters [noDupeKeys](https://docs.rome.tools/lint/rules/noDupeKeys) -> noDuplicatedObjectKeys

Agree with avoiding abbreviations. I implemented `noDupeKeys` and didn't think much of it, but I wouldn't pick this name now that I think about it, it just came straight from ESLint.

I would suggest these names:
[noDupeArgs](https://docs.rome.tools/lint/rules/noDupeArgs) -> noDuplicateArguments
[noDupeKeys](https://docs.rome.tools/lint/rules/noDupeKeys) -> noDuplicatePropertyNames
Arguments and parameters are not the same thing, it should keep being called arguments. I would avoid going for something overly specific, e.g. saying *object* keys might be confusing later if we also apply it to, say, [records](https://github.com/tc39/proposal-record-tuple). Property names might be clearer than keys.

Discussion might be going out of scope though since this appears to be just about the groups. I can re-suggest this on another issue for a rule names cleanup. Might be good to get some consistency in now because there are still few rules and many still in nursery so it's all not too breaking.

**Comment by jeysal** [comment]
> [noDupeArgs](https://docs.rome.tools/lint/rules/noDupeArgs) -> noDuplicatedFunctionParameters [noDupeKeys](https://docs.rome.tools/lint/rules/noDupeKeys) -> noDuplicatedObjectKeys

Agree with avoiding abbreviations. I implemented `noDupeKeys` and didn't think much of it, but I wouldn't pick this name now that I think about it, it just came straight from ESLint.

I would suggest these names:
[noDupeArgs](https://docs.rome.tools/lint/rules/noDupeArgs) -> noDuplicateArguments
[noDupeKeys](https://docs.rome.tools/lint/rules/noDupeKeys) -> noDuplicatePropertyNames
Arguments and parameters are not the same thing, it should keep being called arguments. I would avoid going for something overly specific, e.g. saying *object* keys might be confusing later if we also apply it to, say, [records](https://github.com/tc39/proposal-record-tuple). Property names might be clearer than keys.

Discussion might be going out of scope though since this appears to be just about the groups. I can re-suggest this on another issue for a rule names cleanup. Might be good to get some consistency in now because there are still few rules and many still in nursery so it's all not too breaking.

**Comment by Conaclos** [comment]
> Arguments and parameters are not the same thing

Could you develop about that?

`Arguments` could be confusing because of js implicit `arguments` variable. By the way, I assimilate arguments to actual parameters and I assimilate parameters to formal parameters.

If `noDuplicateArguments` is preffered over `noDuplicateFunctionParameters`, I should certainly rename `noDefaultFunctionParameterLast` to something like `noDefaultArgumentLast`?

**Comment by jeysal** [comment]
> > Arguments and parameters are not the same thing
> 
> Could you develop about that?

We're going a bit off topic in this PR 😅 but yeah so basically iirc arguments refers to something that a function takes and parameters to the values that you pass to it when you call the function, that then become concrete "instances" of the arguments for that function call. This is why I think it is called no duplicate arguments and not no duplicate parameters.

**Comment by MichaReiser** [comment]
> > > Arguments and parameters are not the same thing
> 
> > 
> 
> > Could you develop about that?
> 
> 
> 
> We're going a bit off topic in this PR 😅 but yeah so basically iirc arguments refers to something that a function takes and parameters to the values that you pass to it when you call the function, that then become concrete "instances" of the arguments for that function call. This is why I think it is called no duplicate arguments and not no duplicate parameters.

It's the other way round. You pass arguments in a call to a function that is parametrised by function parameters 

https://stackoverflow.com/a/156787

https://tc39.es/ecma262/#sec-parameter-lists

**Comment by jeysal** [comment]
Oops sorry, thanks for looking it up. Typed it on my phone yesterday from memory which was apparently wrong. In that case `noDuplicateParameters` is good. Funny that ESLint also got it wrong (probably naming was also not thought too much about there)

**Comment by Conaclos** [comment]
I could also suggest adding `Function` in the name, such as `noDuplicateFunctionParameters`, in order to distinguish them from generic parameters.

**Comment by leops** [comment]
I ended up renaming `noDupeKeys` to `noDuplicateObjectKeys`, and `noDupeArgs` to `noDuplicateParameters`. I didn't include `Function` in the latter with the rationale that the rule works on more than "Function" nodes (it also works on methods), and that we may eventually extend it to detect not just duplicated formal parameters but also generic parameters

**Comment by xunilrj** [comment]
Makes sense to have specific groups for frameworks?
I would love to move `useExhaustiveDependencies` and `useHooksAtTopLevel` to a React specific group.

**Review by ematipico — APPROVED** [review]

**Comment by leops** [comment]
> Have you performed any testing on the promoted rules on real-world projects like ESLint?

I've tested the newly recommended rules (`complexity/useFlatMap`, `correctness/useValidForDirection`, `suspicious/noExplicitAny` and `correctness/noConstAssign`) on the ESLint repo and they are not raising any error. Also I don't think I mentioned it at the time but I had run a similar test when I enabled the recommended nursery rules on unstable builds already, so I had already removed the `recommended` flag for rules that had high false positive rates.

**Pull request merged**
