### PR TITLE
chore(rome_js_syntax): Delete the unused `JsConstructorParameter` kind

### PR DESCRIPTION
**Pull request by MichaReiser**
## Summary

This PR deletes the unused `JsSyntaxKind::JS_CONSTRUCTOR_PARAMETER`. 

## Test Plan

`cargo build`

### CODE REVIEW

**Review by ematipico — APPROVED** [review]
I wonder if there's a way to generate these kinds from the grammar.. or make sure there aren't dangling keywords like in this example.

**Comment by MichaReiser** [comment]
> I wonder if there's a way to generate these kinds from the grammar.. or make sure there aren't dangling keywords like in this example.

Yes, that would be a nice improvement. @IWANABETHATGUY would this be something you have an interest in?

**Comment by IWANABETHATGUY** [comment]
> 

Yeah, let us open an issue to track this task.

**Comment by IWANABETHATGUY** [comment]
Could we guarantee that all the node in `KIND_SRC.nodes` are defined in `xx.ungram` ?
More specifically, `SET(KIND_SRC.nodes)` == `SET(xx.ungram.definition)` ?

**Comment by MichaReiser** [comment]
> `KIND_SRC`

I'm not entirely sure what you're saying. What I understand is if it is guaranteed that all nodes are defined in the `.ungram` file and there are no other nodes (or tokens). 

I think this is safe to assume because any node that isn't defined in the `ungram` file won't have a corresponding AST node.

**Comment by IWANABETHATGUY** [comment]
> defined

I mean if some node_kind defined in `KIND_SRC.nodes` https://github.com/rome/tools/blob/5654fae83798224905e7f9c5a6fb9c79b9f9b125/xtask/codegen/src/kinds_src.rs#L187  but not in `xx.ungram` file, vice versa, it will not be safe to apply your advice the generating code would be broken.

**Comment by IWANABETHATGUY** [comment]
sorry for my poor expression.

**Pull request merged**
