### PR TITLE
feat(editors): add Restart LSP Server command

### LINKED ISSUE #3524: Add a "Rome: Restart LSP Server" command?
### Discussed in https://github.com/rome/tools/discussions/3202

<div type='discussions-op-text'>

<sup>Originally posted by **lgarron** September 10, 2022</sup>
### Environment information

```bash
macOS 12.5.1
VSCode v1.71.0
Rome extension v0.14.1
```

### What happened?

While adopting Rome for an existing codebase, I regularly need to edit `rome.json` and work with the revisited changes. There is currently no way to restart the LSP from the command palette other than the very heavy-handed "Reload Window" command. This has several undesirable side effects, such as losing recent file edit (undo) history.

### Expected result

It would be nice to have a "Restart LSP Server" command, similar to other LSP extensions.

Automatically updating the LSP config when `rome.json` changes (#3195) would go a significant way towards many of the use cases for a "Restart LSP Server" command.

But there are some cases where it's useful to restart the LSP server even when `rome.json` hasn't changed, such as when you are re-compiling the LSP binary in-place (e.g. because you're recompiling it from scratch during developement/debugging of Rome itself).

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct</div>

### PR DESCRIPTION
**Pull request by kaioduarte**
## Summary
Closes #3524

## Test Plan

https://user-images.githubusercontent.com/11046907/198582133-cc61345e-ed8a-4d1c-91f2-88b5280db41e.mov

### CODE REVIEW

**Review by leops — COMMENTED** [review]
Interestingly while this does have the intended effect of reloading the configuration, this does not actually restart the server process, it's only closing the existing connection to the server and opening a new one. Because we don't currently persist or share workspace instances across sessions it goes through the whole initialization and loading of the configuration again, but it be useful to stop an old version of the Rome server to stop and start a new instance from the latest version.

**Comment by MichaReiser** [comment]
> Interestingly while this does have the intended effect of reloading the configuration, this does not actually restart the server process, it's only closing the existing connection to the server and opening a new one. Because we don't currently persist or share workspace instances across sessions it goes through the whole initialization and loading of the configuration again, but it be useful to stop an old version of the Rome server to stop and start a new instance from the latest version.

How would you recommend implementing such a command. Issue the stop command right before calling into `restart`?

**Comment by leops** [comment]
> > Interestingly while this does have the intended effect of reloading the configuration, this does not actually restart the server process, it's only closing the existing connection to the server and opening a new one. Because we don't currently persist or share workspace instances across sessions it goes through the whole initialization and loading of the configuration again, but it be useful to stop an old version of the Rome server to stop and start a new instance from the latest version.
> 
> How would you recommend implementing such a command. Issue the stop command right before calling into `restart`?

Unfortunately sending the `stop` command will cause the server to exit immediately while the client is still active, so the server will be immediately restarted by the auto-restart behavior of the default error handler in the client library. Ideally we would be able to call `client.stop()` in a way that doesn't cause it to dispose of the connection to the server so that we could issue the `rome/stop` request once the state of the extension has been fully cleaned up but that's not something the client library allows by default. We would either have to wrap the connection object we return to the client to prevent it from being closed while the client is being stopped, or re-implement the default error handler in our own code so we could inhibit the auto-restart behavior while we send the stop request.

**Comment by MichaReiser** [comment]
@leops That sounds significantly more complicated. 

Do you agree that the current solution addresses the problem where a user restarts the rome server to clear any client-specific state? And thus, merging it would improve the user experience?

**Comment by ematipico** [comment]
I was about to say the same thing that Leo said. This PR doesn't solve the real problem.

>  merging it would improve the user experience?

For example, if the user updates the rome binary inside the `package.json`, using this command won't solve the issue. So we are on square one. **We could merge it**, although we still tell to tell the user what are our limitations.

I planned to have a section called `Known limitations` in the `README.md` of the extension, you can see it here: https://github.com/rome/tools/pull/3526/files#diff-26e0392cd342e5ae4128c6f6bb669e6326537400604fb0a843332a2293f5cdb9

**Comment by leops** [comment]
> Do you agree that the current solution addresses the problem where a user restarts the rome server to clear any client-specific state? And thus, merging it would improve the user experience?

I think it's still worth it to merge this change, and we could also point the user to the `rome stop` command in the meantime

**Review by ematipico — APPROVED** [review]

**Pull request merged**
