### PR TITLE
feat(lint): Add optional call expression support to preferOptianalChaining linting rule

### PR DESCRIPTION
**Pull request by antonk52**
## Summary

This PR is a follow up to #1143 & #1231. Now the rule also marks the code that can be written using optional call expressions as an error. Besides adding the OCE support I've also improved the auto fix to preserve the leading and trailing comment from the original code for OCE and optional member expressions.

## Test Plan

I've added the test cases for OCE and the once that check that the comment preservation works.

I have not yet pushed the auto fix for discovered `check` problems to see the CI output in GH actions

### CODE REVIEW

**Comment by ematipico** [comment]
@antonk52 it seems your rule caught some bugs :) would you mind checking them? 

Could you please change the title of your PR? https://github.com/rome/tools/blob/main/CONTRIBUTING.md#creating-pull-requests

It should start with `feat(lint): `

**Comment by antonk52** [comment]
Hi, @ematipico I've initially left off the autofixes so it would be easier to review the changes.

I've regenerated files and applied autofixes. Should be good to go now.

Please note that I've added suppressions for the `website` directory since Netlify uses an older version of nodejs which does not support optional call expressions.


PS: I've rebased my branch with the current main branch and now I'm having an issue that file paths are not being detected when passed to the rome cli command, ie `./rome check ./website`

As a result I get this output:

```sh
▲ ./rome check ./website
✔ Connected to daemon

 argv:1:11 args/fileNotFound ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ No matching lint files found

    rome check ./website --no-programmatic
               ^^^^^^^^^ website
```

I've been able to reproduce it on both my branch and current main branch with nodejs versions 16.0 and 14.16.1. I can also confirm that `process.cwd()` returns the correct directory. Should I create a separate issue? Not sure if it is related to #1437

**Comment by ematipico** [comment]
>  Netlify uses an older version of nodejs which does not support optional call expressions.

How does Netlify interact with the JS that we ship on our website?

**Comment by ematipico** [comment]
BTW, I couldn't replicate the issue you mentioned. I run the same command with and without daemon running. No issues were thrown.

**Comment by antonk52** [comment]
> How does Netlify interact with the JS that we ship on our website?

When [this script](https://github.com/rome/tools/blob/4bee16144fec6d1a749dc4b25a7ef789c136d9f9/website/src/_includes/layouts/funding.liquid#L24) is getting included the liquid template engine(?) fails parsing the file when gets to `?.` and netlify cannot build the website with an error `unexpected "."`

> BTW, I couldn't replicate the issue you mentioned. I ran the same command with and without daemon running. No issues were thrown.

The problem went away once I've restarted my computer 🙂 I've created #1458 incase other people come across it to trouble shoot further.

**Review by ematipico — APPROVED** [review]

**Pull request merged**
