### PR TITLE
fix(rome_cli): Use lines() separator for os independent git ignore pa…

### PR DESCRIPTION
**Pull request by m1212e**
## Summary

This PR fixes parsing issues with the .gitignore files on windows. Currently the lines of the read .gitignore are separated by `\n` which causes the parsing to break with `\r\n`. The `lines()` method does fix this behavior.

## Changelog

- [x] The PR requires a changelog line

## Documentation

- [ ] The PR requires documentation
- [ ] I will create a new PR to update the documentation

### CODE REVIEW

**Review by ematipico — CHANGES_REQUESTED** [review]
Thank you for your contribution! I'd ask you the following changes:
- restore the PR template and fill it 
- add a changelog line, as explained in the [contribution guide](https://github.com/rome/tools/blob/main/CONTRIBUTING.md#changelog)
- add a new test case with a gitignore file that has CRLF

**Comment by ematipico** [comment]
Closes https://github.com/rome/tools/issues/4556

**Comment by m1212e** [comment]
Sure, I hope this is correct? Tbh this is the first time that I pr a repo with changelog requirements, please excuse any mistakes :D
I don't really understand how the tests work and where to add it, would that be in https://github.com/m1212e/tools/blob/a3de5f50d348359e9c2e27a7046bf912de6d7a73/crates/rome_cli/tests/commands/check.rs#L1793 ? Did I overlook docs on how the tests are structured?

**Comment by m1212e** [comment]
Ok, I had to read about snapshot tests but thats actually pretty cool, I hope this is correct?

**Review by ematipico — APPROVED** [review]
Fantastic, thank you for your contribution! ❤️

**Pull request merged**
