### PR TITLE
fix(rome_js_parser): 🐛TsModuleDeclaration name should allow builtin types

### LINKED ISSUE #2959: 🐛 Parser: `TsModuleDeclaration` name should allow builtin types
### Environment information

[Playground](https://play.rome.tools/?code=module+number+%7B%7D&lineWidth=80&indentStyle=tab&quoteStyle=double&indentWidth=2&sourceType=module&typescript=true&jsx=true#bQBvAGQAdQBsAGUAIABuAHUAbQBiAGUAcgAgAHsAfQA=)

Found in [NativeScript](https://github.com/NativeScript/NativeScript/blob/main/packages/types-android/src/lib/android/android-platform-31.d.ts)

### What happened?

```
module number {}
module string {}
```

errored with

```
error[SyntaxError]: Type alias cannot be number
  ┌─ main.js:1:8
  │
1 │ module number {}
  │        ^^^^^^

error[SyntaxError]: Type alias cannot be string
  ┌─ main.js:2:8
  │
2 │ module string {}
  │        ^^^^^^

```

### Expected result

No error.

---

p.s. This [NativeScript](https://github.com/NativeScript/NativeScript/blob/main/packages/types-android/src/lib/android/android-platform-31.d.ts) file is huge, and it took ~1.5s to parse, there's probably a bottleneck somewhere.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
## Summary
1. Fixed #2959 
2. Some of `is_reserved_type_name` is allowed in `TsModuleDeclaration` but not in `interface` and `type` alias, you could see more details here https://github.com/rome/tools/issues/2959#issuecomment-1198930538 

## Test Plan
1. Should pass all  testcases newly added.

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
!bench_parser

**Comment by IWANABETHATGUY** [comment]
!bench_parser

**Comment by IWANABETHATGUY** [comment]
Seems this patch introduce a lot regression, I will take a look latter.

**Comment by MichaReiser** [comment]
I recommend you to rebase on main (have you rebased past the LTO optimisation) and run the perf tests locally. I wouldn't expect this change to have any significant performance impact.

**Comment by IWANABETHATGUY** [comment]
!bench

**Comment by IWANABETHATGUY** [comment]
!bench_parser

**Comment by IWANABETHATGUY** [comment]
!bench_parser

**Review by MichaReiser — APPROVED** [review]

**Pull request merged**
