### PR TITLE
chore: Upgrade rust dependencies

### PR DESCRIPTION
**Pull request by MichaReiser**
## Summary

Upgrades our dependencies 

```
    Updating crates.io index
    Updating anyhow v1.0.53 -> v1.0.62
    Updating async-trait v0.1.52 -> v0.1.57
    Updating autocfg v1.0.1 -> v1.1.0
    Updating backtrace v0.3.65 -> v0.3.66
    Updating bumpalo v3.9.1 -> v3.11.0
    Updating bytemuck v1.11.0 -> v1.12.1
    Updating bytes v1.1.0 -> v1.2.1
    Updating cast v0.2.7 -> v0.3.0
    Updating cc v1.0.72 -> v1.0.73
    Updating countme v3.0.0 -> v3.0.1
    Updating crc32fast v1.3.1 -> v1.3.2
    Updating criterion v0.3.5 -> v0.3.6
    Updating criterion-plot v0.4.4 -> v0.4.5
    Updating crossbeam v0.8.1 -> v0.8.2
    Updating crossbeam-channel v0.5.2 -> v0.5.6
    Updating crossbeam-deque v0.8.1 -> v0.8.2
    Updating crossbeam-epoch v0.9.6 -> v0.9.10
    Updating crossbeam-queue v0.3.5 -> v0.3.6
    Updating crossbeam-utils v0.8.6 -> v0.8.11
    Updating ctor v0.1.21 -> v0.1.23
      Adding cuckoofilter v0.5.0
    Removing dashmap v4.0.2
    Removing dashmap v5.2.0
      Adding dashmap v5.3.4
    Updating dissimilar v1.0.3 -> v1.0.4
    Updating either v1.6.1 -> v1.8.0
    Updating expect-test v1.2.2 -> v1.4.0
    Updating fastbloom-rs v0.3.0 -> v0.3.1
    Updating filetime v0.2.15 -> v0.2.17
    Updating flate2 v1.0.22 -> v1.0.24
    Updating flume v0.10.10 -> v0.10.14
    Updating futures v0.3.19 -> v0.3.23
    Updating futures-channel v0.3.19 -> v0.3.23
    Updating futures-core v0.3.19 -> v0.3.23
    Updating futures-executor v0.3.19 -> v0.3.23
    Updating futures-io v0.3.19 -> v0.3.23
    Updating futures-macro v0.3.19 -> v0.3.23
    Updating futures-sink v0.3.19 -> v0.3.23
    Updating futures-task v0.3.19 -> v0.3.23
    Updating futures-util v0.3.19 -> v0.3.23
    Removing getrandom v0.2.4
      Adding getrandom v0.1.16
      Adding getrandom v0.2.7
    Updating gimli v0.26.1 -> v0.26.2
    Updating globset v0.4.8 -> v0.4.9
    Updating hdrhistogram v7.5.0 -> v7.5.1
    Updating httparse v1.5.1 -> v1.7.1
    Updating itoa v1.0.1 -> v1.0.3
    Updating js-sys v0.3.58 -> v0.3.59
    Updating libc v0.2.129 -> v0.2.132
    Updating libz-sys v1.1.3 -> v1.1.8
    Updating lock_api v0.4.6 -> v0.4.7
    Removing miniz_oxide v0.4.4
    Updating mio v0.8.2 -> v0.8.4
    Removing miow v0.3.7
    Removing ntapi v0.3.6
    Updating num-traits v0.2.14 -> v0.2.15
    Updating object v0.28.4 -> v0.29.0
    Updating once_cell v1.13.0 -> v1.13.1
    Updating parking_lot v0.12.0 -> v0.12.1
    Updating parking_lot_core v0.9.1 -> v0.9.3
    Updating pin-project v1.0.10 -> v1.0.12
    Updating pin-project-internal v1.0.10 -> v1.0.12
    Updating pin-project-lite v0.2.8 -> v0.2.9
    Updating pkg-config v0.3.24 -> v0.3.25
    Updating plotters v0.3.1 -> v0.3.2
    Updating plotters-backend v0.3.2 -> v0.3.4
    Updating plotters-svg v0.3.1 -> v0.3.2
      Adding ppv-lite86 v0.2.16
    Updating proc-macro2 v1.0.40 -> v1.0.43
    Updating pulldown-cmark v0.9.1 -> v0.9.2
    Updating quote v1.0.15 -> v1.0.21
    Removing rand v0.8.4
      Adding rand v0.7.3
      Adding rand v0.8.5
      Adding rand_chacha v0.2.2
      Adding rand_core v0.5.1
      Adding rand_hc v0.2.0
    Updating redox_syscall v0.2.10 -> v0.2.16
    Updating rgb v0.8.31 -> v0.8.33
    Removing rustc_version v0.4.0
    Updating rustls v0.20.2 -> v0.20.6
    Updating ryu v1.0.9 -> v1.0.11
    Removing semver v1.0.4
    Updating serde v1.0.138 -> v1.0.143
    Updating serde_derive v1.0.138 -> v1.0.143
    Updating serde_json v1.0.82 -> v1.0.83
    Updating serde_repr v0.1.7 -> v0.1.9
    Updating similar v2.1.0 -> v2.2.0
    Updating similar-asserts v1.2.0 -> v1.4.2
    Updating slab v0.4.5 -> v0.4.7
    Updating smallvec v1.8.0 -> v1.9.0
    Updating spin v0.9.2 -> v0.9.4
    Updating syn v1.0.98 -> v1.0.99
    Updating thiserror v1.0.30 -> v1.0.32
    Updating thiserror-impl v1.0.30 -> v1.0.32
    Updating tinyvec v1.5.1 -> v1.6.0
    Updating tokio v1.17.0 -> v1.20.1
    Updating tokio-macros v1.7.0 -> v1.8.0
    Updating tokio-util v0.7.1 -> v0.7.3
    Updating toml v0.5.8 -> v0.5.9
    Updating tower v0.4.12 -> v0.4.13
    Updating tower-service v0.3.1 -> v0.3.2
    Updating tracing v0.1.34 -> v0.1.36
    Updating tracing-attributes v0.1.20 -> v0.1.22
    Updating tracing-core v0.1.23 -> v0.1.29
    Updating tracing-log v0.1.2 -> v0.1.3
    Updating tracing-subscriber v0.3.11 -> v0.3.15
    Updating tracing-tree v0.2.0 -> v0.2.1
    Updating trybuild v1.0.56 -> v1.0.64
    Updating ungrammar v1.14.9 -> v1.16.1
    Updating unicode-bidi v0.3.7 -> v0.3.8
    Updating unicode-ident v1.0.2 -> v1.0.3
    Updating unicode-normalization v0.1.19 -> v0.1.21
    Updating unicode-segmentation v1.8.0 -> v1.9.0
    Updating ureq v2.4.0 -> v2.5.0
    Updating wasi v0.10.2+wasi-snapshot-preview1 -> v0.9.0+wasi-snapshot-preview1
    Updating wasm-bindgen v0.2.81 -> v0.2.82
    Updating wasm-bindgen-backend v0.2.81 -> v0.2.82
    Updating wasm-bindgen-macro v0.2.81 -> v0.2.82
    Updating wasm-bindgen-macro-support v0.2.81 -> v0.2.82
    Updating wasm-bindgen-shared v0.2.81 -> v0.2.82
    Updating web-sys v0.3.58 -> v0.3.59
    Updating webpki-roots v0.22.2 -> v0.22.4
    Updating windows-sys v0.32.0 -> v0.36.1
    Updating windows_aarch64_msvc v0.32.0 -> v0.36.1
    Updating windows_i686_gnu v0.32.0 -> v0.36.1
    Updating windows_i686_msvc v0.32.0 -> v0.36.1
    Updating windows_x86_64_gnu v0.32.0 -> v0.36.1
    Updating windows_x86_64_msvc v0.32.0 -> v0.36.1
      Adding xorfilter-rs v0.5.1
```

## Test Plan

`cargo test`

### CODE REVIEW

**Comment by MichaReiser** [comment]
!bench_parser

**Comment by MichaReiser** [comment]
!bench_analyzer

**Comment by MichaReiser** [comment]
!bench_formatter

**Comment by ematipico** [comment]
> ### Analyzer Benchmark Results
> 
> ```
> group                     main                                   pr
> -----                     ----                                   --
> analyzer/css.js           1.00      2.2±0.01ms     5.3 MB/sec    1.03      2.2±0.01ms     5.2 MB/sec
> analyzer/index.js         1.00      5.9±0.05ms     5.5 MB/sec    1.03      6.1±0.10ms     5.3 MB/sec
> analyzer/lint.ts          1.00      3.1±0.03ms    13.4 MB/sec    1.06      3.3±0.07ms    12.7 MB/sec
> analyzer/parser.ts        1.00      7.2±0.12ms     6.7 MB/sec    1.08      7.8±0.18ms     6.2 MB/sec
> analyzer/router.ts        1.00      5.2±0.12ms    11.9 MB/sec    1.07      5.5±0.10ms    11.2 MB/sec
> analyzer/statement.ts     1.00      6.9±0.12ms     5.1 MB/sec    1.04      7.2±0.15ms     4.9 MB/sec
> analyzer/typescript.ts    1.00     10.2±0.14ms     5.3 MB/sec    1.05     10.6±0.23ms     5.1 MB/sec
> ```

This is a bit unsettling 😮

**Review by ematipico — COMMENTED** [review]
Why no `Cargo.toml` file was updated? 🤔

**Comment by IWANABETHATGUY** [comment]
> 

https://doc.rust-lang.org/cargo/commands/cargo-update.html#description
`cargo update` will only update `cargo.lock`

**Comment by IWANABETHATGUY** [comment]
> 

Why the passed `js/262/` test case plus 1?

**Comment by MichaReiser** [comment]
> > 
> 
> Why the passed `js/262/` test case plus 1?

Pico args removed the functionality to parse `option=value` by default. So I had to add it again and that seems to fix the plus 1.

**Comment by MichaReiser** [comment]
bench_formatter!

**Comment by MichaReiser** [comment]
bench_parser!

**Comment by MichaReiser** [comment]
bench_analyzer!

**Comment by MichaReiser** [comment]
!bench_formatter

**Comment by MichaReiser** [comment]
!bench_parser

**Comment by MichaReiser** [comment]
!bench_analyzer

**Review by leops — APPROVED** [review]

**Review by ematipico — APPROVED** [review]

**Comment by MichaReiser** [comment]
> > > 
> > 
> > 
> > Why the passed `js/262/` test case plus 1?
> 
> Pico args removed the functionality to parse `option=value` by default. So I had to add it again and that seems to fix the plus 1.

I've been wrong before. The reason why the test has been added is because it previously failed with

```
[xtask/coverage/src/js/test262.rs:169] read_metadata(&code) = Err(
    Custom {
        kind: InvalidData,
        error: Scan(
            ScanError {
                mark: Marker {
                    index: 87,
                    line: 1,
                    col: 87,
                },
                info: "mapping values are not allowed in this context",
            },
        ),
    },
)
```

which we silently ignore. So my guess is that this has been fixed inside serde's parser. 


I'm still a bit concerned by the performance regression, mainly becomes I'm unable to tell where it's coming from.

**Comment by MichaReiser** [comment]
These are my local results

```
group                                    main                                    upgrade
-----                                    ----                                    -------
analyzer/css.js                          1.00  1174.2±34.00µs     9.9 MB/sec     1.00  1174.6±25.70µs     9.9 MB/sec
analyzer/index.js                        1.00      3.2±0.01ms    10.1 MB/sec     1.07      3.4±0.26ms     9.4 MB/sec
analyzer/lint.ts                         1.00  1776.6±169.15µs    23.4 MB/sec    1.03  1824.2±168.18µs    22.8 MB/sec
analyzer/parser.ts                       1.00      3.9±0.23ms    12.3 MB/sec     1.05      4.1±0.34ms    11.8 MB/sec
analyzer/router.ts                       1.04      3.0±0.28ms    20.3 MB/sec     1.00      2.9±0.23ms    21.2 MB/sec
analyzer/statement.ts                    1.00      3.9±0.29ms     9.2 MB/sec     1.05      4.1±0.39ms     8.7 MB/sec
analyzer/typescript.ts                   1.00      6.2±0.56ms     8.8 MB/sec     1.03      6.4±0.48ms     8.5 MB/sec
formatter/checker.ts                     1.00   210.6±11.03ms    12.3 MB/sec     1.09   229.0±21.18ms    11.4 MB/sec
formatter/compiler.js                    1.00    129.7±1.46ms     8.1 MB/sec     1.01    131.6±7.87ms     8.0 MB/sec
formatter/d3.min.js                      1.01    112.5±9.35ms     2.3 MB/sec     1.00   111.0±16.45ms     2.4 MB/sec
formatter/dojo.js                        1.00      7.3±0.02ms     9.4 MB/sec     1.12      8.2±0.48ms     8.4 MB/sec
formatter/ios.d.ts                       1.00    143.1±0.62ms    13.0 MB/sec     1.04   148.8±13.28ms    12.5 MB/sec
formatter/jquery.min.js                  1.00     28.8±1.58ms     2.9 MB/sec     1.04     30.0±2.78ms     2.8 MB/sec
formatter/math.js                        1.10   239.9±18.42ms     2.7 MB/sec     1.00    218.8±1.23ms     3.0 MB/sec
formatter/parser.ts                      1.12      5.5±0.46ms     8.9 MB/sec     1.00      4.9±0.12ms     9.9 MB/sec
formatter/pixi.min.js                    1.18    142.7±1.65ms     3.1 MB/sec     1.00    120.8±7.18ms     3.6 MB/sec
formatter/react-dom.production.min.js    1.01     36.7±3.10ms     3.1 MB/sec     1.00     36.1±2.90ms     3.2 MB/sec
formatter/react.production.min.js        1.09  1946.4±151.72µs     3.2 MB/sec    1.00  1783.2±23.75µs     3.4 MB/sec
formatter/router.ts                      1.07      4.2±0.35ms    14.6 MB/sec     1.00      3.9±0.26ms    15.7 MB/sec
formatter/tex-chtml-full.js              1.00   293.3±23.44ms     3.1 MB/sec     1.00   292.5±18.26ms     3.1 MB/sec
formatter/three.min.js                   1.03   144.9±13.13ms     4.1 MB/sec     1.00   140.5±10.78ms     4.2 MB/sec
formatter/typescript.js                  1.00   914.4±63.51ms    10.4 MB/sec     1.01   926.8±67.65ms    10.3 MB/sec
formatter/vue.global.prod.js             1.00     47.7±3.61ms     2.5 MB/sec     1.01     48.1±3.79ms     2.5 MB/sec
parser/checker.ts                        1.03     56.9±0.45ms    45.7 MB/sec     1.00     55.2±0.25ms    47.1 MB/sec
parser/compiler.js                       1.14     41.9±1.24ms    25.0 MB/sec     1.00     36.7±2.49ms    28.5 MB/sec
parser/d3.min.js                         1.00     23.5±2.02ms    11.2 MB/sec     1.05     24.6±1.80ms    10.7 MB/sec
parser/dojo.js                           1.09      2.2±0.22ms    31.4 MB/sec     1.00  1993.3±27.43µs    34.4 MB/sec
parser/ios.d.ts                          1.10     51.4±4.87ms    36.3 MB/sec     1.00     47.0±1.19ms    39.7 MB/sec
parser/jquery.min.js                     1.03      6.7±0.61ms    12.3 MB/sec     1.00      6.5±0.56ms    12.6 MB/sec
parser/math.js                           1.11     47.6±3.27ms    13.6 MB/sec     1.00     43.0±3.75ms    15.1 MB/sec
parser/parser.ts                         1.00   1442.2±4.84µs    33.8 MB/sec     1.08  1551.7±117.25µs    31.4 MB/sec
parser/pixi.min.js                       1.02     25.5±0.22ms    17.2 MB/sec     1.00     24.9±0.13ms    17.6 MB/sec
parser/react-dom.production.min.js       1.14      9.7±0.49ms    11.8 MB/sec     1.00      8.5±0.66ms    13.5 MB/sec
parser/react.production.min.js           1.08   495.1±33.60µs    12.4 MB/sec     1.00   460.4±40.45µs    13.4 MB/sec
parser/router.ts                         1.01  1365.4±108.36µs    45.0 MB/sec    1.00  1348.9±82.36µs    45.6 MB/sec
parser/tex-chtml-full.js                 1.05     54.8±3.44ms    16.6 MB/sec     1.00     52.0±0.48ms    17.5 MB/sec
parser/three.min.js                      1.00     28.5±0.88ms    20.6 MB/sec     1.05     29.9±3.02ms    19.6 MB/sec
parser/typescript.js                     1.02   245.8±19.54ms    38.6 MB/sec     1.00   241.4±13.86ms    39.4 MB/sec
parser/vue.global.prod.js                1.00     11.1±0.91ms    10.9 MB/sec     1.06     11.8±0.71ms    10.2 MB/sec

```

**Pull request merged**
