### PR TITLE
feat(parser): support parsing key remap in mapped types

### PR DESCRIPTION
**Pull request by yeonjuan**
## Summary

It's for supporting `Key Remapping in Mapped Types` which introduced in TS 4.1. (#1244) 

- [ts-4.1 key-remaping-in-mapped-types](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-1.html#key-remapping-in-mapped-types)

```ts
type MappedTypeWithNewKeys<T> = {
    [K in keyof T as NewKeyType]: T[K]
    //            ^^^^^^^^^^^^^
    //            This is the new syntax!
}
```

## Test Plan

I added [a test case and snapshot](https://github.com/rome/tools/compare/main...yeonjuan:ts4-1-key-remap?expand=1#diff-29177e1a4d0172414689c180568fbd0e857a1c8d8c9448dd97a4ba9c5297972d)

### CODE REVIEW

**Comment by ematipico** [comment]
Probably we should check also the formatter part: https://github.com/rome/tools/blob/main/internal/formatter/builders/js/typescript/TSMappedType.ts

Do you prefer doing it in this PR or create a separate PR?

**Comment by yeonjuan** [comment]
@ematipico
> Probably we should check also the formatter part:

Oh, Thanks :) I want to do in this PR

**Comment by yeonjuan** [comment]
@ematipico Thanks :) I changed the formatter part also. Maybe should we add a test case?

**Comment by ematipico** [comment]
@yeonjuan thank you for looking into this! Yes I think we should add a small test case. It could be a starting point, in case in the future we will uncover some edge case.

**Comment by yeonjuan** [comment]
@ematipico Thanks for your review and proposal. :) I added test cases for it. (The CI was failed before but works now. 😅)

**Review by ematipico — APPROVED** [review]
This is 🔥 ! We can now start using the mapped types inside Rome! Huge thanks!

**Pull request merged**
