### PR TITLE
Added `json-schema`

### LINKED ISSUE #3601: 📎 JSON Schema
### Description

Create a JSON schema (following [json-schema](https://json-schema.org/learn/getting-started-step-by-step.html) standard) would be a nice improvement to the configuration file.

I would be happy to help into this. It can be uploaded on the website then (like [turbo](https://turbo.build/schema.json) does.) or  on [SchemaStore](https://github.com/SchemaStore/schemastore)

### LINKED ISSUE #3690: 📎 Allow "$schema" in rome.json
### Description

As a web developer I love good developer experience. For configuration files, JSON schemas are super helpful. I'd like to add `$schema` to my `rome.json`

```json
{
  "$schema": "https://raw.githubusercontent.com/rome/tools/main/editors/vscode/configuration_schema.json",
  "formatter": {
    "indentStyle": "space"
  }
}
```

However, `rome format` fails:

```
> node_modules/.bin/rome --version
Rome CLI version 10.0.1

> node_modules/.bin/rome format --write app/
Error: Rome couldn't load the configuration file, here's why: 
unknown field `$schema`, expected one of `files`, `formatter`, `linter`, `javascript` at line 2 column 11
error Command failed with exit code 1.
```

Related: #3602

### PR DESCRIPTION
**Pull request by Rawnly**
## Summary
Created `schema.json` following the `json-schema` standards to improve DX.
Closes #3601  | Closes #3690

## Test Plan

CleanShot 2022-11-09 at 01 29 57@2x

### CODE REVIEW

**Comment by MichaReiser** [comment]
Thank you @Rawnly for creating the schema. 

I'm unfamiliar with how editors detect a JSON schema. How does the editor know where to look up the document?

We already generated a schema and ship it with the VS Code extension. It should be straightforward to write the same file to multiple locations if it is necessary to publish it on the website too. 

https://github.com/rome/tools/blob/82b9aa7be444cf77b14780ee7591cb750884e573/editors/vscode/configuration_schema.json

**Comment by leops** [comment]
> I'm unfamiliar with how editors detect a JSON schema. How does the editor know where to look up the document?

For the existing schema file, the validation schema is declared to the editor as part of the extension manifest: https://github.com/rome/tools/blob/82b9aa7be444cf77b14780ee7591cb750884e573/editors/vscode/package.json#L101-L106

**Comment by Rawnly** [comment]
> I'm unfamiliar with how editors detect a JSON schema. How does the editor know where to look up the document?

There's a `$schema` key indicating the path to the spec (which can be an url)

**Comment by Rawnly** [comment]
> We already generated a schema and ship it with the VS Code extension. It should be straightforward to write the same file to multiple locations if it is necessary to publish it on the website too.

Oh I didn't noticed that! However the one i generated seems to be a bit more complete, providing key descriptions too. (I generated it running a script on the docs page). I think that description can be useful to avoid switching back and forth with docs.

**Comment by Rawnly** [comment]
I assume this can be closed right? @ematipico

**Comment by ematipico** [comment]
@Rawnly yes :) I took in consideration your feedback about the description of the rules, which is a great one! I couldn't miss it!

**Pull request closed without merging**
