### PR TITLE
fix(parser): parse catch param type in typescript

### PR DESCRIPTION
**Pull request by yeonjuan**
## Summary

Rome fails to parse catch error type.

* target.ts
```ts
try {}
catch (e: unknown) {}
```

```
$ ./rome parse target.ts

  ✖ Unclosed catch clause param

    1 │ try {}
  > 2 │ catch (e: unknown) {}
      │       ^

  ℹ We expected to find the closing character ) here
```

I made a PR to fix it

## Test Plan

test case

### CODE REVIEW

**Comment by ematipico** [comment]
Hi @yeonjuan , thank you for catching this case! Do you think the formatter part works as it should?

**Comment by yeonjuan** [comment]
@ematipico Yes I tested formatter also (in local) :) Should i add the test cases?

**Comment by ematipico** [comment]
Personally, I think we should add a test, to avoid possible future regressions. (and we add a new test which is something where we lack at the moment)

**Comment by yeonjuan** [comment]
@ematipico Thanks for the review :) I add a test case for formatter

**Review by ematipico — APPROVED** [review]

**Pull request merged**
