### PR TITLE
fix(playground): run npm build after wasm-pack

### PR DESCRIPTION
**Pull request by NicholasLYang**

### CODE REVIEW

**Comment by MichaReiser** [comment]
Would it be possible to add a test plan? For example by [manually triggering](https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow) the workflow?

**Comment by NicholasLYang** [comment]
Can you manually trigger a workflow if you add the `workflow_dispatch` trigger in a branch?

**Comment by ematipico** [comment]
> Can you manually trigger a workflow if you add the `workflow_dispatch` trigger in a branch?

Unfortunately, no:

> To run a workflow manually, the workflow must be configured to run on the workflow_dispatch event. **To trigger the workflow_dispatch event, your workflow must be in the default branch**.

**Comment by NicholasLYang** [comment]
Yeah workflows are incredibly frustrating lol. Why isn't there a CLI to validate a workflow config???

**Comment by MichaReiser** [comment]
> Yeah workflows are incredibly frustrating lol. Why isn't there a CLI to validate a workflow config???

[There is](https://github.com/nektos/act)... but setting it up is painful

**Pull request merged**
