### PR TITLE
fix(playground): malformed prettier formating result

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
## Summary
1. Downgrade `vite` to `2.9.5`

## Test Plan
1. No need to test I guess, or you could run the code locally.

### CODE REVIEW

**Comment by vramana** [comment]
How can Vite be the problem here?

**Comment by IWANABETHATGUY** [comment]
> How can Vite be the problem here?



> How can Vite be the problem here?

So what do you think the problem is?

**Comment by MichaReiser** [comment]
Thanks @IWANABETHATGUY for looking into this. Can you provide some additional information on what the exact problem is that you're solving? E.g. what's your test plan to verify that this change is indeed fixing the problem (and maybe add some additional description on what problem this PR is solving in the first place)? 

Is this solving the [object Object] that occasionally appears in the playground? If so, then I expect this to be a race condition inside of our react code. I would suspect some misbehaving between initializing the context from the URL params and the first time the `effect` updating the URL runs.

**Comment by ematipico** [comment]
> Thanks @IWANABETHATGUY for looking into this. Can you provide some additional information on what the exact problem is that you're solving? E.g. what's your test plan to verify that this change is indeed fixing the problem (and maybe add some additional description on what problem this PR is solving in the first place)?
> 
> Is this solving the [object Object] that occasionally appears in the playground? If so, then I expect this to be a race condition inside of our react code. I would suspect some misbehaving between initializing the context from the URL params and the first time the `effect` updating the URL runs.

The issue that this fix solves  happens only in production, only on the prettier output. All the lines after the first one have an additional level of indentation.

**Comment by IWANABETHATGUY** [comment]
Because I don't have permission to deploy playground,so I add a screenshot:
## Current  (production build and serve the static `/dist` via `live-server`)
image
## Main
image

**Review by MichaReiser — APPROVED** [review]

**Pull request merged**
