### PR TITLE
refactor(rome_js_analyze): groups

### PR DESCRIPTION
**Pull request by ematipico**
## Summary

> **Note**: This PR is a highly disruptive. It also changes the documentation of the website. Maybe we should merge before the next release.

Relevant discussion https://github.com/rome/tools/discussions/3017#discussioncomment-3567594

This PR refactor the group names, please read the relevant discussion for more details.

## Test Plan

Updated documentation, CLI tests, analyzer tests. The CI should pass because no new functionality has been implemented.

### CODE REVIEW

**Review by MichaReiser — APPROVED** [review]

**Review by leops — CHANGES_REQUESTED** [review]
Some of the snapshots are detected by Git as having been deleted and added instead of being moved (`flipBinExp`, `inlineVariable`, `noLabelVar`, `noNegationElse`), I think this may indicate they haven't been moved to the correct directory as the resulting snapshot content is different enough that Git doesn't detect it as the same file

**Comment by ematipico** [comment]
> Some of the snapshots are detected by Git as having been deleted and added instead of being moved (`flipBinExp`, `inlineVariable`, `noLabelVar`, `noNegationElse`), I think this may indicate they haven't been moved to the correct directory as the resulting snapshot content is different enough that Git doesn't detect it as the same file

I fixed the snapshots, but for `noLabelVar` there's something strange: the old snapshot didn't have any diagnostic and the new one (the correct one) now has the diagnostic

**Comment by leops** [comment]
> > Some of the snapshots are detected by Git as having been deleted and added instead of being moved (`flipBinExp`, `inlineVariable`, `noLabelVar`, `noNegationElse`), I think this may indicate they haven't been moved to the correct directory as the resulting snapshot content is different enough that Git doesn't detect it as the same file
> 
> I fixed the snapshots, but for `noLabelVar` there's something strange: the old snapshot didn't have any diagnostic and the new one (the correct one) now has the diagnostic

For `noLabelVar` I think it was the other way around, the file wasn't in the correct directory in the first place, but it is now

**Review by leops — COMMENTED** [review]
The diagnostics for `noNegationElse` are still missing from the snapshots, I think we should have a safety check in the analyzer tests that verifies the path of the snapshots files correspond to the rule instead of failing silently

**Review by leops — APPROVED** [review]

**Pull request merged**
