### PR TITLE
feat(css-prefix): add border-image support

### PR DESCRIPTION
**Pull request by imskr**
## Summary

- Added `border-image` support
- Contributes to #1423 

## Test Plan

- `./rome test`

### CODE REVIEW

**Review by ematipico — APPROVED** [review]

**Comment by ematipico** [comment]
Thank you! Can you please rebase and run `./script generate-all-files`?

**Comment by imskr** [comment]
@ematipico Done

**Comment by ematipico** [comment]
@imskr sorry, need to it again! Unfortunately we can only merge on PR at the time

**Comment by imskr** [comment]
> @imskr sorry, need to it again! Unfortunately we can only merge on PR at the time

No problem, Done

**Pull request merged**
