### PR TITLE
fix(rome_js_semantic):should push a new scope when meet a function expression

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
## Summary
1. Fix missing push scope event when meeting a function expression. 
2. e.g.
 ```js
var test = function test(a, b, c) {
//              ^^^^^^^^^^^^^^^^^^^ should push a new scope
}
```
https://play.rome.tools/?code=var+test+%3D+function+test%28a%2C+b%2C+c%29+%7B%0A%0A%7D&lineWidth=80&indentStyle=tab&quoteStyle=double&indentWidth=2&sourceType=module&typescript=false&jsx=false#dgBhAHIAIAB0AGUAcwB0ACAAPQAgAGYAdQBuAGMAdABpAG8AbgAgAHQAZQBzAHQAKABhACwAIABiACwAIABjACkAIAB7AAoACgB9AA==

## Test Plan
1. Should pass newly added semantic test case.

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
!bench_analyzer

**Review by xunilrj — APPROVED** [review]

**Comment by xunilrj** [comment]
Mind creating some extra tests?

```js
var f/*#F1*/ = function f/*#F2*/() {console.log(f/*READ F2*/);}",
```

```js
var f/*#F1*/ = function () {console.log(f/*READ F1*/);}",
```

```js
let f/*#F1*/ = 1; let g = function f/*#F2*/() {console.log(2, f/*READ F2*/);}",
```

```js
let f/*#F*/ = function g/*#G*/(){}; g/*?*/();",
```

The last one needs a new assertion "?" that matches ```UnresolvedReference```

**Comment by IWANABETHATGUY** [comment]
> Mind creating some extra tests?
> 
> ```js
> var f/*#F1*/ = function f/*#F2*/() {console.log(f/*READ F2*/);}",
> ```
> 
> ```js
> var f/*#F1*/ = function () {console.log(f/*READ F1*/);}",
> ```
> 
> ```js
> let f/*#F1*/ = 1; let g = function f/*#F2*/() {console.log(2, f/*READ F2*/);}",
> ```
> 
> ```js
> let f/*#F*/ = function g/*#G*/(){}; g/*?*/();",
> ```
> 
> The last one needs a new assertion "?" that matches `UnresolvedReference`

Done

**Comment by xunilrj** [comment]
Approved.

**Review by leops — APPROVED** [review]

**Pull request merged**
