### PR TITLE
feat(rome_js_analyze): new rule noCondAssign

### PR DESCRIPTION
**Pull request by 95th**
## Summary

Implement eslint's [`no-cond-assign`](https://eslint.org/docs/latest/rules/no-cond-assign) lint.

## Test Plan

Added unit tests.

### CODE REVIEW

**Review by MichaReiser — APPROVED** [review]
Nice to see how straightforward the implementation is thanks to the separation of expression/assignments in the AST.

**Comment by MichaReiser** [comment]
!bench_analyzer

**Review by leops — COMMENTED** [review]
Given the nature of the rule, I think we could provide a suggested fix to replace the assignment expression with a `===` binary expression

**Comment by 95th** [comment]
> Given the nature of the rule, I think we could provide a suggested fix to replace the assignment expression with a `===` binary expression

It could be incorrect in some cases.
For example, traversing a linked list, you could have 
```js
do {} while (node = node.next)
```
Suggesting the below seem bad:
```js
do {} while (node === node.next)
```

**Comment by leops** [comment]
> > Given the nature of the rule, I think we could provide a suggested fix to replace the assignment expression with a `===` binary expression
> 
> It could be incorrect in some cases

I think that's acceptable as long it's only a "suggested fix" with `Applicability::MaybeIncorrect`, as the name indicates it's allowed to be incorrect and should not be applied automatically without a manual review by the user unlike a "safe fix" with `Applicability::Always`

**Comment by 95th** [comment]
@leops Is it ok if I take it up in a followup PR?

**Review by leops — APPROVED** [review]

**Pull request merged**
